### ISSUE TITLE
Does Chaquopy support multiple Python background instances?

### ISSUE THREAD

**Issue by adamryczkowski** [chaquo/chaquopy#1004]
I am planning to write a Kotlin app that supports user-supplied Python addons (for different form of computation). 

I would prefer each addon to run on a dedicated Python instance, so they cannot interfere with each other.

I can get the functionality by spawning a background Python thread for each addon in my custom driver code written in Python. Each spawned thread would load the user-supplied Python addon itself with `importlib`. 

I would prefer a situation where Chaquopy manages the threads itself by allowing spawning multiple Python interpreters. That would be easier to debug, and less error-prone.

**Comment by mhsmith** [comment]
Chaquopy does not support multiple Python instances in the same process. However, if you really need the addons to not interfere with each other, then you'd need to run them as separate processes anyway.

There's an example of doing this in the [chaquopy-jupyter](https://github.com/chaquo/chaquopy-jupyter) repository. It won't build in its current state, but the main points are:

* In app/src/main/AndroidManifest.xml, the `android:process` setting declares a service that runs in a separate process. You can have as many services as you want.
* In app/src/debug/python/chaquopy/jupyter/notebook.py, the service is started and stopped with the `startService` and `stopService` methods.
* In app/src/debug/java/com/chaquo/python/jupyter/KernelService.java, the start and stop commands are received in the other process, where they manage their own instance of Python.

You'd also need to come up with some way for the processes to communicate with each other. Other than the start and stop commands, you won't find many details of that in this example, because it's all handled by Jupyter.
