### ISSUE TITLE
Please add opencv-contrib-python package

### ISSUE THREAD

**Issue by nonsobiose** [chaquo/chaquopy#102]

**Comment by mhsmith** [comment]
Thanks for the request. This package isn't a priority at the moment, but we'd probably be willing to add it in return for a small payment: please [email us](https://chaquo.com/chaquopy/contact/) if you're interested in this.

If anyone else wants this package too, please subscribe to this issue and add a thumbs up.

**Comment by TheForgetTime** [comment]
I also need this package.
I tried to compile this package but it failed.

**Comment by mhsmith** [comment]
This issue is fixed in Chaquopy 7.0.2. To upgrade, edit your app's top-level build.gradle file and change the version number of `com.chaquo.python:gradle` to `7.0.2`.

Please review the [release notes](https://chaquo.com/chaquopy/doc/current/changelog.html), especially the point about most native packages having been upgraded.
