### ISSUE TITLE
Invalid build warning: Index url seems invalid

### ISSUE THREAD

**Issue by IsakTheHacker** [chaquo/chaquopy#1029]
#### Chaquopy version

14.0.2

#### Relevant parts of your build.gradle file

```
ndk {
    abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
}

python {
    version "3.8"

    pip {
        options "--extra-index-url", rootProject.projectDir.toString() + "/wheels"
    }

    pyc {
        stdlib true
        pip true
        src true
    }
}
```

#### Describe your issue

I first get this error
```
The index url "<project-path>/wheels" seems invalid, please provide a scheme.
```

Then for every package that I don't build myself, and instead use the official repository I get this warning
```
Url '<project-path>/wheels/frozenlist/' is ignored. It is either a non-existing path or lacks a specific scheme.
```

It would be nice to silence these warnings since they don't affect the build in any way.

**Comment by mhsmith** [comment]
These warnings are harmless, but I agree they're confusing. Even worse, if you actually do provide a `file:` scheme, then pip starts looking for index.html files rather than just listing the directory.

One alternative is to put all of your wheels in the same directory, without separate subdirectories per package, and then pass that path to the [`--find-links`](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-f) option. Unfortunately, this is a different directory layout to the one that comes out of the package build tool.

**Comment by IsakTheHacker** [comment]
Okay, so I only actually have one custom package in the wheels directory: Cryptography. Would the warnings go away if I just replace this line:
```
options "--extra-index-url", rootProject.projectDir.toString() + "/wheels"
```
with this:
```
options "--find-links", rootProject.projectDir.toString() + "/wheels/cryptography"
```

Also, can I pass multiple `--find-links` parameters if I add more packages and don't want to change the directory layout? Maybe, for upcoming Chaquopy releases, it would be possible to suppress these warnings with a filter in the Gradle plugin?

**Comment by mhsmith** [comment]
Yes, using `--find-links` in that way should work.

The long-term solution is to move to the current version of pip, see if it still has problems in this area, and fix them in pip itself if possible.

**Comment by IsakTheHacker** [comment]
Excellent, that solves my problem
