### ISSUE TITLE
Android UI Demo using Jetpack Compose

### ISSUE THREAD

**Issue by Heus-Sueh** [chaquo/chaquopy#1064]
Is there a way to use jetpack compose with chaquopy? If so, it would be cool to have a demo of using it together with Python

Here are several ready-made demos of Material3 and Jetpack Compose made by Google. It would be cool to adapt a demo for Python:
https://github.com/android/compose-samples
![image](https://github.com/chaquo/chaquopy/assets/98482469/d98a4ace-bd44-4941-a51f-81b5f7c8b1f4)

same as android ui demo:
https://github.com/chaquo/chaquopy/blob/master/demo/app/src/main/python/chaquopy/demo/ui_demo.py

**Comment by Flyfish233** [comment]
There is literally no significant difference in usage between implementing Chaquopy in XML or in Jetpack Compose, my ongoing project using View Model, Kotlin Flow and Coroutine to handle Chaquopy output.

**Comment by Heus-Sueh** [comment]
I just saw that you can't use Jetpack Compose with java only Kotlin

**Comment by mhsmith** [comment]
It makes no difference whether your app uses Java or Kotlin, or Views or Compose, because they can all call the Chaquopy Java API just as easily.

However, we no longer recommend using Chaquopy to write Android user interfaces in Python – if you want to do that, please check out [BeeWare](https://beeware.org/).
