### ISSUE TITLE
can I use eval() function ??

### ISSUE THREAD

**Issue by lawiparadise** [chaquo/chaquopy#1119]
I tried this code, but doesn't working

![image](https://github.com/chaquo/chaquopy/assets/12179624/b57a2116-6489-4074-a03b-81b571603051)

with this error
com.chaquo.python.PyException: SystemError: frame does not exist
![image](https://github.com/chaquo/chaquopy/assets/12179624/3456f485-083c-4c1a-bbc3-a6b1a15a147b)

please help me...TT

thank you!

**Comment by mhsmith** [comment]
Please don't post screenshots of text. Copy the text and mark it with triple backticks as shown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).

Also, when posting exceptions, please include the FULL stack trace.

In this case, I think the relevant part of the [`eval` documentation](https://docs.python.org/3/library/functions.html#eval) is:

> If the locals dictionary is omitted it defaults to the globals dictionary. If both dictionaries are omitted, the expression is executed with the globals and locals in the environment where [eval()](https://docs.python.org/3/library/functions.html#eval) is called.

Since you're not calling the function from a Python environment, it's unable to do this. You can work around this by passing an empty dict as the second argument of `eval`.

**Comment by mhsmith** [comment]
> so it's not a problem of secondary & third argument I think

I think it is. Try this:
```
py.builtins.callAttr("eval", "1+4", py.builtins.callAttr("dict"))
```
