### ISSUE TITLE
'import pyhrv' gets 'no module tkinter error'

### ISSUE THREAD

**Issue by ChaeYeon01** [chaquo/chaquopy#1145]
#### Chaquopy version

15.0

#### Relevant parts of your code

python script
import cv2
import numpy as np
import time
import pyhrv

build.gradle
chaquopy{
    defaultConfig {
        version = "3.8"
        pip{
            install("opencv-python")
            install("numpy")
            install("spectrum")
            install("scipy")
            install("pyhrv")
        }
    }

#### Describe your issue

I need to import pyhrv. 
but when I import pyhrv, I get
com.chaquo.python.PyException: ModuleNotFoundError: No module named 'tkinter'
(Even if I don't put any funtion of pyhrv, just only import pyhrv, it says same error)

I know chaquopy doesn't support tkinter.
But I don't need to use tkinter. I don't use and write it anywhere.
Is pyhrv using tkinter??? Is pyhrv related to tkinter?

Why does pyhrv out tkinter error although I don't use tkinter? 
And how can I use pyhrv without tkinter error?

**Comment by mhsmith** [comment]
Please post the full stack trace, as described at https://stackoverflow.com/a/23353174.

**Comment by ChaeYeon01** [comment]
Oh I'm so sorry..!

here:

![pyhrv_main](https://github.com/chaquo/chaquopy/assets/91841696/75c353b2-c4a3-4581-bc6b-ee2ac03f2e36)
![pyhrv_main2](https://github.com/chaquo/chaquopy/assets/91841696/65dda652-c53a-4eee-a635-582ad1b8e57e)

**Comment by mhsmith** [comment]
I suggest you report this to the biosppy project, and request them to tolerate the situation where tkinter is unavailable.

Unfortunately I can't see any simple workaround. Adding a fake tkinter module to `sys.modules` isn't enough, because [biosppy/inter_plotting/ecg.py](https://github.com/scientisst/BioSPPy/blob/main/biosppy/inter_plotting/ecg.py) also unconditionally imports `matplotlib.backends.backend_tkagg`.
