### ISSUE TITLE
Update GitHub actions version in workflow files from 16.x (deprecated and soon unsupported) to 20.x

### ISSUE THREAD

**Issue by IsakTheHacker** [chaquo/chaquopy#1173]
I just went through the recent actions logs out of curiosity and noticed that this repo is using outdated GitHub actions based on NodeJS 16.x. These are deprecated and support for them in the runners will eventually be removed. I'm posting an issue here first to see if this is something that you would want help with perhaps? One proposal is to just use dependabot to create automatic update PRs for all major version updates to these GitHub actions. What do you think?

Also just wanted to thank you for creating such an amazing project. For me, this has been a big inspiration for my own projects, and I've learnt a lot by studying the code and software architecture of Chaquopy. Maybe I can't help with the more advanced things but if there is something that is just regular maintenance or a small feature I would love to send some patches :)

**Comment by mhsmith** [comment]
Thanks very much, and thanks for all your contributions so far.

I think using dependabot to automatically update to every version, or even every major version, causes more work in the long run. I prefer to stay on known-good versions where possible, and only update if there's a specific reason to do so. 

But since these versions have actually been deprecated, I would certainly accept a PR to update them.
