### ISSUE TITLE
Subprocess appears to not work

### ISSUE THREAD

**Issue by daniel-sudz** [chaquo/chaquopy#125]
I am trying to run a python script from a python script in order to pass in a command line arguments.

I have used the following commands on windows but inside of chaquopy they appear to have no effect and do not print anything to stder or stdout. 

Script1:

```
def runscript2:
    import subprocess
    subprocess.Popen("script2.py 1", shell=True)
```

Script2: 
```
print("test")
```

Script1 is called like so in java:
 
```
py = Python.getInstance();
PyObject test_run= py.getModule("Script1");
test_run.callAttr("runscript2");
```
</pre>

**Comment by mhsmith** [comment]
Chaquopy doesn't include a separate Python executable: everything is run within your main app process. So you won't be able to launch a Python script this way.

If the only reason you're trying to launch a new process is to pass command line arguments, then you can set the arguments by modifying `sys.argv` before importing `script2`.  In order to run the script multiple times, just delete it from sys.modules and then import it again. Or [`runpy.run_module`](https://docs.python.org/3/library/runpy.html#runpy.run_module) might also be useful here.

Alternatively, you could restructure `script2` so it can be called as a function, like this:

```
def main(*args):
   ...

if __name__ == "__main__":
    main(*sys.argv)
```

And then call it like this:

```
import script2
script2.main("1")
```

**Comment by daniel-sudz** [comment]
Appending my arguments to sys.argv worked perfectly for my use case. Thanks for the help!
