### ISSUE TITLE
build issue with pip install librosa, pip install noisereduce

### ISSUE THREAD

**Issue by ShiaoFuk** [chaquo/chaquopy#1297]
```
   ERROR: Command errored out with exit status 1:
     command: 'X:\pythonEnv\Scripts\python.exe' -S -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\10904\\AppData\\Local\\Temp\\pip-install-xun81ep5\\matplotlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\10904\\AppData\\Local\\Temp\\pip-install-xun81ep5\\matplotlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base pip-egg-info
         cwd: C:\Users\10904\AppData\Local\Temp\pip-install-xun81ep5\matplotlib\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\10904\AppData\Local\Temp\pip-install-xun81ep5\matplotlib\setup.py", line 40, in <module>
        import setupext
      File "C:\Users\10904\AppData\Local\Temp\pip-install-xun81ep5\matplotlib\setupext.py", line 19, in <module>
        from pybind11.setup_helpers import Pybind11Extension
    ModuleNotFoundError: No module named 'pybind11'
 ```
   
   when I was installing noisereduce by pip the error occur.
   the same problem with pip install librosa "no module name Cpython" though I had added "install CPython". 
   If somebody could solve I would sincerely appreciate!!!

**Comment by mhsmith** [comment]
For `librosa`, see https://github.com/chaquo/chaquopy/issues/834#issuecomment-1485745722.

`noisereduce` installs fine for me. If you still have problems, please post:
* The complete build log – to show it, click the “Build: failed” caption to the left of the error.
* The relevant parts of your build.gradle file
* The Chaquopy version you're using

**Comment by ShiaoFuk** [comment]
the same problem occur while installing "audiomentations"

**Comment by mhsmith** [comment]
I think you must be using an old version of Chaquopy which doesn't use the current repository. Check the version of `com.chaquo.python` in your app's top-level build.gradle file, and update it to be [as new as possible](https://chaquo.com/chaquopy/doc/current/changelog.html).

Even then, the current version of `audiomentations` still won't install:

* It requires newer versions of `numba` and `numpy` than we currently have for Python 3.8. It might be possible to work around this by using an older version of `audiomentations`, just as you already are for `librosa`.

* It requires `msgpack`, for which there's a workaround  [here](https://github.com/chaquo/chaquopy/issues/1001#issuecomment-1763807212).

* It requires `numpy-rms` and `numpy-minmax`, which we don't currently support at all. This also might be possible to work around by using an older version of `audiomentations`; otherwise, you'll have to [build them yourself](https://github.com/chaquo/chaquopy/blob/master/server/pypi/README.md).
