### ISSUE TITLE
Module ImportError no module named six, on 0.4.4

### ISSUE THREAD

**Issue by aez90** [chaquo/chaquopy#13]
I'm getting an `ImportError: No module named six` while trying to test out Chaquopy for Android. I can see the `six.py` file in the .zip archive and I've installed `six` in my python distribution (which was reinstalled from scratch).

I'm running Chaquopy 0.4.4, Python 2.7.10 and Gradle 2.3.3. This seems related to a closed issue on relative imports and import hooks but that was supposed to be fixed with 0.4.4. Happy to share any logs/version numbers I can generate.

(I also posted on [SO](https://stackoverflow.com/questions/46939418/chaquopy-android-import-error), I wasn't sure what was preferred).

**Comment by mhsmith** [comment]
Thanks for the report: this will be fixed in the next release. In the meantime, you can work around the problem by building `six` into your app using the `pipInstall` directive, as is done by the demo app [here](https://github.com/chaquo/chaquopy/blob/d88d4207ec8239c3b1f8f15cf3e89192f140fe0f/app/build.gradle#L33).

**Comment by mhsmith** [comment]
Fixed in version 0.4.5.
