### ISSUE TITLE
Fatal signal 11 (SIGSEGV) when importing cartopy

### ISSUE THREAD

**Issue by ytremare** [chaquo/chaquopy#1300]
App crash with fatal error in libc.
Fork is available at: https://github.com/ytremare/chaquopy-16.0.0
note that chaquopy-16.0.0 is the chaquopy version of chaquopy (github people told me it wasn't possible to have 2 forks of the same repository ) but packages are up to date and the build version is 14.0.2.

#### Chaquopy version com.chaquo.python:gradle:14.0.2'

Debug trace below
```
art_sigsegv_fault:
	pushq  %rbp                     
	pushq  %r14                     
	pushq  %rbx                     
	subq   $0x10, %rsp              
	movq   %fs:0x28, %rax           
	movq   %rax, 0x8(%rsp)          
	movq   0x6f0f9b(%rip), %rax     
	cmpb   $0x0, 0xd(%rax)          
	jne    0x4684dc                   ; <+60>
	movq   %fs:0x28, %rax           
	cmpq   0x8(%rsp), %rax          
	jne    0x468543                   ; <+163>
	addq   $0x10, %rsp              
	popq   %rbx                     
	popq   %r14                     
	popq   %rbp                     
	retq                            
	movl   $0x2, %edi               
	xorl   %esi, %esi               
	callq  0x9484e0                   ; symbol stub for: android::base::ShouldLog(android::base::LogSeverity, char const*)
	testb  %al, %al                 
	je     0x4684c3                   ; <+35>
	callq  0x948540                   ; symbol stub for: __errno
	movq   %rax, %rbx               
	movl   (%rax), %ebp             
	leaq   -0x39a18b(%rip), %rsi    
	movq   %rsp, %r14               
	movq   %r14, %rdi               
	movl   $0x32, %edx              
	movl   $0x2, %ecx               
	xorl   %r8d, %r8d               
	movl   $0xffffffff, %r9d          ; imm = 0xFFFFFFFF
	callq  0x9484f0                   ; symbol stub for: android::base::LogMessage::LogMessage(char const*, unsigned int, android::base::LogSeverity, char const*, int)
	movq   %r14, %rdi               
	callq  0x948500                   ; symbol stub for: android::base::LogMessage::stream()
	leaq   -0x39bf12(%rip), %rsi    
	movl   $0x47, %edx              
	movq   %rax, %rdi               
	callq  0x3beeb0                   ; std::__1::basic_ostream<char, std::__1::char_traits<char>>& std::__1::__put_character_sequence<char, std::__1::char_traits<char>>(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, char const*, unsigned long)
	movq   %r14, %rdi               
	callq  0x948520                   ; symbol stub for: android::base::LogMessage::~LogMessage()
	movl   %ebp, (%rbx)             
	jmp    0x4684c3                   ; <+35>
	callq  0x94ad10                   ; symbol stub for: __stack_chk_fail
```

Crash occurs on the following instruction:
import cartopy.feature as cf
import  cartopy provides also libc crash

App without any change was working on my previous laptop. I've checked a lot of things but didn't succeed to find what is wrongly set or configured on the laptop. I also copied cartopy from old laptop to the new one, result is the same.
Wheels are correctly generated generated .
My guess is there some mistake at laptop side , but I'm unable to find it.

You'll find also attached build.gradle.log file.
[build.gradle-log.txt](https://github.com/user-attachments/files/17938616/build.gradle-log.txt)

**Comment by ytremare** [comment]
Thanks for your quick response.
The guilty instruction is **import cartopy.feature as cf**
App call 2 python scripts, the first one is to initialize python environment for app, the second one is the functional script, it's in charge to load read and decode grib file(grib are weather forecast data).
In the logcat you 'll see that decoding is working fine. Decoding and reading are based on cfgrib associated to eccodes (native lib). When python attempt to project data on map, it imports cartopy. putting import cartopy leads to have crash with "no module name ", but no libc crash. 
Please find attached full logcat/
here below full error msg.
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 21874 (ibdownloaderapp), pid 21874 (ibdownloaderapp)
[logcat.txt](https://github.com/user-attachments/files/17949196/logcat.txt)

**Comment by mhsmith** [comment]
libc is provided by the device itself. It's involved in reporting the crash, but it's unlikely to be the cause of the problem.

This log still doesn't contain any more information about the crash. There should be a native backtrace that looks something like the ones in https://github.com/chaquo/chaquopy/issues/1209#issuecomment-2212443248. To find it in the logcat, you may need to display all messages rather than just the ones from your own app.

**Comment by ytremare** [comment]
got it. I'm willing to update github.
Seems due to unreadable libs.
Thx

Yves



Le mer. 4 déc. 2024 à 18:40, Malcolm Smith ***@***.***> a
écrit :

**Comment by ytremare** [comment]
Adding full logcat
[full_logcat.txt](https://github.com/user-attachments/files/18012542/full_logcat.txt)

**Comment by mhsmith** [comment]
Thanks very much. Unfortunately this still doesn't give a clear indication of the cause, except that it involves `libc++`, which we released a new version of recently.

The new version is supposed to be backward compatible with the old one, and it works with almost all the existing packages, but we had to rebuild a couple which experienced native crashes (#1171). It's possible one of your packages has a similar issue.

I don't really understand what you're saying at the top of this issue about Chaquopy 14.0.2 and 16.0.0. If you built these .whl files using build-wheel from the 14.0.2 tag, then you will have used NDK version 22, with the old libc++ version. To make sure your app uses the same version at runtime, you can add `install "chaquopy-libcxx==11000"` to your build.gradle file. 

However, we've fixed lots of bugs since then, so I recommend you try updating your app to Chaquopy 16.0.0, and rebuilding the .whl files with the current version of build-wheel (i.e. the head of the master branch, *not* the 16.0.0 tag). This produces .whl files with an API level of 24, so your app's `minSdk` will need to be 24 or greater.

**Comment by ytremare** [comment]
hi.
Using chaquopy-libcxx==11000 fix the issue.
I already attempt to use chaquopy 16.0.0 but I face to an issue (
https://github.com/chaquo/issues/1287#top
<https://github.com/chaquo/chaquopy/issues/1287#top>)
The new NDK(ie 27.1)  seems involved.
I'll retry with chaquopy 16.0.0.later on.
Yves Trémaré
06 38 32 19 95


Le mer. 4 déc. 2024 à 19:42, Malcolm Smith ***@***.***> a
écrit :

**Comment by ytremare** [comment]
Fixed chaquopy-libcxx==11000.
Thanks for your efficient suppot.
