### ISSUE TITLE
Using Chaquopy without android

### ISSUE THREAD

**Issue by Kingnaoufal** [chaquo/chaquopy#1301]
Hi,

I wonder if it's possible to use Chaquopy in a regular Java application using Maven ?

Thanks,
NB

**Comment by mhsmith** [comment]
We don't officially release or support Chaquopy for any platform other than Android. However, it is possible to build it for the development machine's own platform using the following Gradle tasks in the `product` project:

* `runtime:cmake-host` – build the libraries
* `runtime:testPython` – test Java embedded in Python
* `runtime:testJava` – test Python embedded in Java

In theory this should work on Linux, Mac and Windows, but since I currently develop on a Mac, that's the only one I regularly test. Linux in particular has one known problem (#1201).
