### ISSUE TITLE
Library resampy doesn't install

### ISSUE THREAD

**Issue by raymondklutse** [chaquo/chaquopy#133]
I am trying to install resampy version 0.2.1 but it keeps failing. Is there a way to get it done? Thank you

**Comment by mhsmith** [comment]
Like librosa (#21), resampy requires numba, which we don't currently support. However, we've had quite a few requests for it, so we'll probably look into it within the next couple of months.

**Comment by mhsmith** [comment]
This issue is fixed in Chaquopy 7.0.2. To upgrade, edit your app's top-level build.gradle file and change the version number of `com.chaquo.python:gradle` to `7.0.2`.

Please review the [release notes](https://chaquo.com/chaquopy/doc/current/changelog.html), especially the point about most native packages having been upgraded.
