### ISSUE TITLE
"PackageNotFoundError: importlib_metadata", but I have it installed

### ISSUE THREAD

**Issue by liyanhrxy** [chaquo/chaquopy#198]
![image](https://user-images.githubusercontent.com/32901980/71172189-89c63e00-229a-11ea-9f56-9aa3f2a896fd.png)

**Comment by mhsmith** [comment]
Thanks, we'll take a look at this. Meanwhile, you can work around it by using `jsonschema==3.0.2` or older, which doesn't require `importlib_metadata`.

**Comment by mhsmith** [comment]
This issue is fixed in Chaquopy 7.0.2. To upgrade, edit your app's top-level build.gradle file and change the version number of `com.chaquo.python:gradle` to `7.0.2`.

Please review the [release notes](https://chaquo.com/chaquopy/doc/current/changelog.html), especially the point about most native packages having been upgraded.
