### ISSUE TITLE
Multithreaded crash in python console 

### ISSUE THREAD

**Issue by ddddx** [chaquo/chaquopy#199]
Android5.1.1, using multithreading in python console , when the thread finishes running, the application crashes
But works fine in android 8/9

![device-2019-12-30-104652](https://user-images.githubusercontent.com/22161743/71566339-c0e5ec00-2af1-11ea-8555-5b7b95cffca2.png)

![RQIUL0KFY1}VJ_@I8L69JU](https://user-images.githubusercontent.com/22161743/71566413-5b462f80-2af2-11ea-9834-78038ce0f436.png)

**Comment by mhsmith** [comment]
If you're using the low-level `_thread` API, you'll need to detach the thread manually, as described in [the documentation](https://chaquo.com/chaquopy/doc/current/python.html#multi-threading). I know it says this only applies to threads which use the `java` module, but actually your thread will use that module indirectly by calling `print`, because the console app redirects stdout to the GUI.

If possible I recommend you use the high-level `threading` API instead, in which case this will be handled automatically.
