### ISSUE TITLE
Missing stdlib modules

### ISSUE THREAD

**Issue by fl0wmaster** [chaquo/chaquopy#20]
I am in the process of making sympy available in your environment but found no support for:

doctest (standard in python 3), available through import.
distutils (standard in python 3)

This prevents me to continue the project, there are simply to many dependencies on these modules to work around them.

When these are available it might be that more is required, I cannot see this right now.....

Hope you consider incorporating support for these modules.

**Comment by mhsmith** [comment]
Thanks for the report, we'll take a look at it.

Internal issue id: 5160

**Comment by mhsmith** [comment]
Fixed in Chaquopy 1.2.0. If your app was using Python 2.7.10, you'll also need to update that to 2.7.14. If you were using Python 3.6.3, then you can leave it unchanged.

I'm not familiar with sympy, but I've tried some basic things from the documentation and it seems to work fine now. However, it does take a long time to import: it looks like it's loading several hundred modules.

I've added sympy and its dependency mpmath to our wheel repository, so you won't need to use your own builds anymore.

**Comment by fl0wmaster** [comment]
Wow, thats great, thanks very much for your support.

**Comment by mhsmith** [comment]
The slow import issue was [fixed in Chaquopy 2.0.0](https://chaquo.com/chaquopy/doc/current/changelog.html#id7).

**Comment by pathak0311** [comment]
how do i import numpy and matplotlib in build.gradle (Android Studio)?

**Comment by mhsmith** [comment]
See [the documentation here](https://chaquo.com/chaquopy/doc/current/android.html#requirements).
