### ISSUE TITLE
pandas from_dict() got an unexpected keyword argument 'columns'

### ISSUE THREAD

**Issue by massicalic** [chaquo/chaquopy#211]
When i try to create a dataframe, i have an error:

df_signaures = pd.DataFrame.from_dict(d, orient = 'index', columns = list_all_subject)

com.chaquo.python.PyException: TypeError: from_dict() got an unexpected keyword argument 'columns'

The function is correct, it also requires the argument "columns"

**Comment by mhsmith** [comment]
The columns argument was added in Pandas version 0.23: we currently only provide version 0.22.

We'll release a new build in the next few weeks: please subscribe to this issue to be notified.

**Comment by mhsmith** [comment]
This issue is fixed in Chaquopy 7.0.2. To upgrade, edit your app's top-level build.gradle file and change the version number of `com.chaquo.python:gradle` to `7.0.2`.

Please review the [release notes](https://chaquo.com/chaquopy/doc/current/changelog.html), especially the point about most native packages having been upgraded.
