### ISSUE TITLE
When  will  the  python bindings for opencv4 be coming  from chaquopy ?

### ISSUE THREAD

**Issue by wwtghx** [chaquo/chaquopy#212]
As title , thanks

**Comment by mhsmith** [comment]
We'll be updating all packages when we move Chaquopy to Python 3.8. Release will probably be in February.

**Comment by kmf909** [comment]
is scipy v1.4.1 included?

**Comment by mhsmith** [comment]
Yes, they will be. We're currently waiting on the release of Android Studio 3.6, and the new Chaquopy version will come out shortly after that.

**Comment by mhsmith** [comment]
This issue is fixed in Chaquopy 7.0.2. To upgrade, edit your app's top-level build.gradle file and change the version number of `com.chaquo.python:gradle` to `7.0.2`.

Please review the [release notes](https://chaquo.com/chaquopy/doc/current/changelog.html), especially the point about most native packages having been upgraded.
