### ISSUE TITLE
Is it possible to use Keras?

### ISSUE THREAD

**Issue by LuArtur** [chaquo/chaquopy#221]
tried to import a model from a neural network using keras  `from keras.models import load_model`
and sends me the following error 

> This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
I have read other issues with the same error but I do not understand if keras can be used with chaquopy

**Comment by mhsmith** [comment]
Unless it throws an exception, that's probably just a warning, not an error.

If it does throw an exception, please post the stack trace.

**Comment by LuArtur** [comment]
![Captura de pantalla de 2020-02-10 13-29-31](https://user-images.githubusercontent.com/60788857/74199953-9b411c00-4c33-11ea-9916-5cc3b11dc3d3.png)

**Comment by mhsmith** [comment]
When I try this with the current version of Keras (2.3.1), I get a different error (AttributeError: module 'tensorflow.python.keras.backend' has no attribute 'get_graph'). What version are you using?

Anyway, as the [Keras website](https://keras.io/) says, their recommendation is to use `tf.keras` instead of installing the standalone keras package. That way there should be no compatibility issues.

**Comment by LuArtur** [comment]
I am using version 2.1.1 of keras but I do not use tensorflow I use theano.  I'm going to check the official keras page and try version 2.3.1

**Comment by mhsmith** [comment]
I was able to get keras and theano working with their current versions as of September 2018 (https://github.com/chaquo/chaquopy/issues/37#issuecomment-419902648). You can find out what those versions were by looking at the packages' PyPI pages.

However, performance was very poor because there was no native compiler available. And as you probably know, theano has now been abandoned. So I'd recommend you move to TensorFlow if possible.

**Comment by LuArtur** [comment]
I tried with version 2.3.1 of keras and received this warning 

>  WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.

how could i solve it

**Comment by mhsmith** [comment]
In my tests in 2018, theano still worked after giving this warning, but was very slow. I have no solution except to move to TensorFlow.

**Comment by LuArtur** [comment]
ok, in the demo of chaquopy when starting the console says that it has the version of gcc 4.9 in linux. Is it necessary to install gcc? Could this solve the warning?

**Comment by mhsmith** [comment]
That's just the version of GCC that Python was built with: there's no compiler actually installed on the device. You might be able to install one yourself, but I have no experience of doing so.

**Comment by LuArtur** [comment]
I have tried to use tensorflow and I receive the following exception
com.chaquo.python.PyException: AttributeError: module 'tensorflow.python.keras.backend' has no attribute 'get_graph'
![stack trace](https://user-images.githubusercontent.com/60788857/74610341-71b74300-50c0-11ea-8f87-33426430c203.png)

**Comment by mhsmith** [comment]
As I said above, the recommendation is to use `tf.keras` instead of installing the standalone keras package. If you'd searched for that error message, you would have found https://github.com/keras-team/keras/issues/12379, which recommends the same thing.

Alternatively, you could probably use an older version of Keras which is compatible with this version of TensorFlow. Have a look at the release history of [Keras](https://pypi.org/project/Keras/#history) and [TensorFlow](https://pypi.org/project/tensorflow/#history), and try versions of Keras which are from about the same time as TensorFlow 1.10.

**Comment by LuArtur** [comment]
I have installed keras 2.2.4 and the problem has been resolved
