### ISSUE TITLE
Update about gradle 3.6.0

### ISSUE THREAD

**Issue by chaocharleswang** [chaquo/chaquopy#225]
When do you update a new version for gradle 3.6.0? Thanks!

**Comment by mhsmith** [comment]
Very soon: within the next few days.

**Comment by mhsmith** [comment]
This issue is fixed in Chaquopy 7.0.2. To upgrade, edit your app's top-level build.gradle file and change the version number of `com.chaquo.python:gradle` to `7.0.2`.

Please review the [release notes](https://chaquo.com/chaquopy/doc/current/changelog.html), especially the point about most native packages having been upgraded.
