### ISSUE TITLE
Support Kotlin build scripts (KTS)

### ISSUE THREAD

**Issue by ghost** [chaquo/chaquopy#231]
How to achieve the same effect in app / build.gradle.kts as app / build.gradle

kts tell me python does not exist in android closure

**Comment by mhsmith** [comment]
`python` doesn't exist directly within the `android` closure: it should be used within `defaultConfig`. Please check [the documentation](https://chaquo.com/chaquopy/doc/current/android.html) and the examples more carefully.

If that still doesn't work, please post the relevant parts of your build scripts.

**Comment by TheForgetTime** [comment]
![捕获](https://user-images.githubusercontent.com/26455845/75848597-9714b280-5e1d-11ea-8385-08e2ca3d1ad4.PNG)

**Comment by mhsmith** [comment]
Please also post the top of the script, where you apply the plugin.

**Comment by TheForgetTime** [comment]
Apply the plugin on the first line using the following Kotlin script

```kotlin
plugins{
    id("com.android.application")
    kotlin("android")
    kotlin("kapt")
    kotlin("android-extensions") 
    id("org.greenrobot.greendao")
    id("com.chaquo.python")
}
```

**Comment by mhsmith** [comment]
Thanks, I'll take a look at it.

**Comment by mhsmith** [comment]
I'm not sure what the exact cause of the problem is. However, [Android doesn't really support kts scripts yet](https://issuetracker.google.com/issues/150436353#comment3), so we probably won't support them either until that changes.

If this issue affects anyone else, please subscribe and give a thumbs up to the original post.

**Comment by BrezPress** [comment]
issue has become more actual

**Comment by mhsmith** [comment]
@BrezPress: Why?

**Comment by BrezPress** [comment]
kotlin dsl is a new standard for android, and to apply this sdk to my project I dont have ideas how to configure  "python.srcDir" in kts.
Step by step...

_project build.gradle.kts_
 ```
  dependencies {
        ...
        classpath("com.chaquo.python:gradle:12.0.1")
    }

```

app build.gradle.kts

```
plugins {
...
    id("com.chaquo.python")
}

android {

    defaultConfig {
               ndk {
            abiFilters.addAll( listOf("armeabi-v7a", "arm64-v8a", "x86", "x86_64"))
        }
     sourceSets {
        named("main") {
            this.????
         //  python.srcDir  = "some/other/dir"
        }
    }
}
```

**Comment by mhsmith** [comment]
We probably won't support KTS build scripts until Google is actually encouraging people to use them, and I don't think that's happening yet.

**Comment by albaspazio** [comment]
from https://developer.android.com/studio/build/migrate-to-kts

[....] In the future, KTS will be preferred over Groovy for writing Gradle scripts because Kotlin is more readable and offers better compile-time checking and IDE support.

In my opinion, google is actually encouraging people to migrate toward kts. I cannot quantify your effort and I assume you may have other priorities, but kts support is something you should implement soon. 

p.s. thanks for your great job

**Comment by aSemy** [comment]
Hi 👋, I'm investigating [a SO question](https://stackoverflow.com/q/74955211/4161471) about Gradle Kotlin DSL support. 

Does the `com.chaquo.python` Gradle plugin use `@CompileStatic`? 

https://docs.gradle.org/7.6/userguide/performance.html#statically_compile_tasks_and_plugins

I suspect that adding this would help with using Groovy from Kotlin.

**Comment by mhsmith** [comment]
You can see the plugin source code [here](https://github.com/chaquo/chaquopy/blob/master/product/gradle-plugin/src/main/groovy/com/chaquo/python/PythonPlugin.groovy). It doesn't currently use `@CompileStatic`, and it makes quite heavy use of Groovy's dynamic features, so making it Kotlin-compatible may be a significant job.

I've made some notes about this which I'll post below.

**Comment by mhsmith** [comment]
[2020-10] 

The Android Studio 4.1 [stable release notes](https://developer.android.com/studio/releases/gradle-plugin#kotlin-script-dsl-support) confirm that KTS is now fully supported. However, KTS is still not mentioned on any of the main documentation pages like [this one](https://developer.android.com/studio/build), and it still isn't an option in the Android Studio new project wizard.

They've also introduced a new [DSL documentation page](https://developer.android.com/reference/tools/gradle-api/) defined in Kotlin syntax only, and a matching `gradle-api` artifact which might be useful, though taking full advantage of it might require rewriting the plugin in Kotlin. Over the next couple of years, [their intention](https://developer.android.com/studio/releases/gradle-plugin-roadmap) is that all interaction between the AGP and other plugins must go through this new API.

So I guess their intention in the long run is to recommend Kotlin over Groovy in build files. Using a statically-typed language should allow much better IDE auto-completion and error highlighting, so if users become used to this for the Android DSL, we should make sure it works for our DSL as well.

**Comment by mhsmith** [comment]
The Kotlin DSL Primer has extensive discussion of [type-safe accessors](https://docs.gradle.org/5.0/userguide/kotlin_dsl.html#type-safe-accessors), but I don't yet understand how they work. 

* Are they still based on ExtensionAware? If so, that might be a problem, because that isn't mentioned in the Android DSL documentation so presumably isn't part of its public API.
* Or does it rewrite the script before passing it to the Kotlin compiler, which must already be happening somehow in order to put plugins on the classpath? 
* Or does it use Kotlin extensions? As it says [here](https://docs.gradle.org/current/userguide/writing_build_scripts.html#sec:the_script_api), "When Gradle executes a Kotlin build script (.gradle.kts), it compiles the script into a subclass of KotlinBuildScript", and [that class](https://gradle.github.io/kotlin-dsl-docs/api/org.gradle.kotlin.dsl/-kotlin-build-script/index.html) has a load of extension properties and functions on the Project class.

Either way, the the [Kotlin DSL Primer](https://docs.gradle.org/current/userguide/kotlin_dsl.html) makes it sound like the new `plugins` syntax will be necessary for this to work.

It might simplify things if we moved the `python` block to the top level of the build.gradle file, and replicated the `android` block structure within it:

```
python {
    defaultConfig {
        buildPython ...
        pip {}
        ...
    }
    buildTypes {}
    productFlavors {}
    sourceSets {
        main {
            python ...
        }
    }
}
```

However, the 2021-10 Android Dev Summit video linked below demonstrates an API which looks like it would allow our current syntax, at least as far as the build types and flavors blocks are concerned (though I'm not sure what the syntax would be in KTS). This video also demonstrates a supported way for a plugin to add assets and other elements to an app, without directly touching any of the AGP's built-in tasks or knowing their names. However, I'm not sure which AGP version these APIs were added in.

In any case, to simplify documentation and testing, if we do create a new syntax then it should be identical in both Kotlin and Groovy, and the old syntax would be kept as a deprecated Groovy-only option.

**Comment by mhsmith** [comment]
[2021-05]

With Android Studio 4.2:

* Every example on the documentation pages has been updated to include both Groovy and Kotlin.
* There's a [Groovy to Kotlin migration guide](https://developer.android.com/studio/build/migrate-to-kts), which confirms "in the future, KTS will be preferred over Groovy".
* The Kotlin option was mentioned in a [Google I/O talk](https://youtu.be/etLUpHvhNZw?t=139). 

However, there's still no option to use KTS in the new project wizard, and even in Arctic Fox Beta 1 (2021-05), the [release notes](https://androidstudio.googleblog.com/2021/05/android-studio-arctic-fox-beta-1.html) say "Kotlin script support is still in preview". In [this video](https://youtu.be/S30XiW05Pho?t=913) they confirm that they intend to move to KTS by default in the future, but are currently blocked by it having lower performance than Groovy.

**Comment by mhsmith** [comment]
Some more relevant links:

* [2019-10 Android Dev Summit video](https://www.youtube.com/watch?v=OTANozHzgPc)
* [2020-07 Medium article](https://medium.com/androiddevelopers/new-apis-in-the-android-gradle-plugin-f5325742e614)
* [2021-05 Google I/O video](https://www.youtube.com/watch?v=AZBW5StgF8o)
* [2021-10 Android Dev Summit video](https://www.youtube.com/watch?v=S_zZRBJxTQ0) (second half), which links to a new documentation page [Extend the Android Gradle plugin](https://developer.android.com/studio/build/extend-agp). However, some of these APIs may only be available in AGP 7.0 and higher.
* [2021-12 series "MAD Skills Gradle and AGP build APIs"](https://android-developers.googleblog.com/2021/12/mad-skills-gradle-and-agp-build-apis.html)
  * In [Episode 6: Live Q&A](https://youtu.be/2FOzPTJprUU?t=1517), an AGP developer says about KTS: "we don't think the ecosystem is quite ready, so it might take a few more years for this to happen".

**Comment by mhsmith** [comment]
According to [this announcement](https://android-developers.googleblog.com/2023/04/kotlin-dsl-is-now-default-for-new-gradle-builds.html), KTS will be used by default in new projects created witn Android Studio Giraffe.

**Comment by albaspazio** [comment]
in the meanwhile.....I wrote a simple tutorial with a suggestion to deal with this issue. 
https://medium.com/p/d9739e95a05a
simply put all python code in a same library module with groovy build language and consume it from other app/lib modules built in kds.

**Comment by mhsmith** [comment]
Thanks, that's a good idea.

**Comment by mhsmith** [comment]
Initially it might seem that the quickest way of doing this is to add a Kotlin layer over the existing Groovy implementation. However, I think it's better to port the existing code to Kotlin and put a Groovy layer over it, because:

* We're using many of the dynamic features of Groovy, and I'm not sure how easy it would be to call them from Kotlin.
* If the Groovy layer is written entirely in terms of the public Kotlin API, then all of the existing Groovy-based tests would automatically cover the Kotlin API as well, so we wouldn't need to add many more tests.
* It would make it easy to remove Groovy support entirely in the future.

**Comment by mhsmith** [comment]
If we end up rewriting the plugin in Kotlin, this would be a good time to switch to the new lazy task configuration API,  which is supported in Android Gradle plugin 3.3 and later.

**Comment by mhsmith** [comment]
If you need to use Chaquopy in a KTS file, try the pre-release build of Chaquopy 15 by following the instructions at https://github.com/chaquo/chaquopy/issues/934#issuecomment-1683205265.
