### ISSUE TITLE
Can i run spleeter on my android app using Chaquopy

### ISSUE THREAD

**Issue by oluwabajio** [chaquo/chaquopy#370]
Hello, 

For some time, i have bee lookig for ways to bid spleeter to my anndroid app (https://github.com/deezer/spleeter).

I came across chaquopy today. 

Please ca i achieve that with chaquopy

**Comment by mhsmith** [comment]
The current version of Chaquopy (8.0.1) uses Python 3.8, which spleeter doesn't yet support (https://github.com/deezer/spleeter/issues/489). 

Chaquopy 6.3.0 was the last version to come with Python 3.6, but it looks like even the oldest version of spleeter [still required TensorFlow 1.14.0](https://github.com/deezer/spleeter/blob/556ef2121492d72398a988af1b38b55176f5973a/setup.py#L20), whereas our Python 3.6 TensorFlow builds were version 1.10.1.

Sorry about that. Once spleeter supports Python 3.8, please give it a try and update this issue if you have any problems.

**Comment by oluwabajio** [comment]
Thanks for your swift response, i appreciate.

**Comment by mhsmith** [comment]
Let's leave the issue open for now in case other people have the same question.

**Comment by mhsmith** [comment]
Spleeter now supports Python 3.8, but it still can't be installed on Chaquopy because it requires specific versions of TensorFlow and Pandas which aren't the same as the ones we provide.

This isn't really a problem with Chaquopy, so I'm closing this issue. If anyone else wants this package, please ask spleeter to make their requirements less specific.
