### ISSUE TITLE
Update Tensorflow

### ISSUE THREAD

**Issue by ajudi46-zz** [chaquo/chaquopy#374]
Is Tensorflow 2.2.0 available for Chaquopy , when i install keras and tensorflow using pip install it says tensorflow need to be 2.2.0 to function with keras

**Comment by mhsmith** [comment]
Chaquopy currently provides TensorFlow 2.1.0, which comes with its own copy of Keras. To use it, simply remove `keras` from your build.gradle file, and replace all references to `keras` in your code with `tensorflow.keras`.

**Comment by mhsmith** [comment]
If anyone else needs a newer version of TensorFlow, please click the thumbs-up button above, and post a comment explaining why you need the new version.

**Comment by hashimi1998** [comment]
I support this suggestion because tensorflow cannot read .h5 model and can only read .pb model. Keras only produce .h5 model.

**Comment by mhsmith** [comment]
I believe our current version of TensorFlow does support .h5 models. If you had a problem with this, then please give details.

**Comment by mhsmith** [comment]
If you're testing with TensorFlow 2.1.0 on another platform, and you get this error:
```
tensorflow_core/python/keras/saving/hdf5_format.py", line 166, in load_model_from_hdf5
model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
```
This is https://github.com/tensorflow/tensorflow/issues/44467, which is an incompatibility between TensorFlow 2.1.0 and h5py 3.x. However, this will not happen on Chaquopy, because our h5py version is 2.10.0. So just run "pip install h5py==2.10.0" to get the matching version on the other platform.

**Comment by mhsmith** [comment]
The EfficientNet models (e.g. `tf.keras.applications.EfficientNetB7`) were added in TensorFlow version 2.3.0 (see #460).

**Comment by alexcarnero97** [comment]
I am trying to load a .h5 trained model on Android Studio but I got the following error: PyException: ValueError: Unknown layer: Functional. I know this happens due to the TensorFlow versions, I trained the model using 2.3.1 version and Android Studio seems to have 2.1.0 version installed. The thing is that I have installed 2.3.1 version using pip correctly (I freeze and I obtain that version), but if I print the tensorflow version from my python script it shows 2.1.0. If I try to specify the tensorflow version in build.gradle I obtain the following error: Could not find a version that satisfies the requirement tensorflow==2.3.1 (from versions: 2.1.0). How can I really upgrade the tensorflow version in Android Studio. Thanks in advance! :)

**Comment by alexcarnero97** [comment]
I have noticed that the latest tensorflow version that Chaquopy supports is 2.1.0 (https://chaquo.com/pypi-7.0/tensorflow/), so that is why it uses that version even though I specify 2.3.1.

**Comment by mhsmith** [comment]
Yes, we currently provide version 2.1.0, so your best option is probably to regenerate your model with the same version.

**Comment by Vixitonian** [comment]
I can't load a saved_model.pb  generated by a version of tensorflow higher than 2.1.0 . It generates an error," JSONDecodeError: Expecting value: line 1 column 1 (char 0)" while running code: tf.keras.models.load_model(saved_model_path)

**Comment by mhsmith** [comment]
Please post the full stack trace.

**Comment by mhsmith** [comment]
On next TensorFlow update, fix #669.

**Comment by TetrixGauss** [comment]
Hello there!! is it possible to add tensorflow==2.7.0 or 2.9.0 and tensorflow-io-gcs-filesystem==0.26.0?

**Comment by mhsmith** [comment]
The full TensorFlow package is extremely difficult to build, so we won't be updating it in the near future. However, tflite-runtime is much easier, so you might be able to update it yourself. See #675 for details.

**Comment by BeMain** [comment]
TensorFlow version 2.3.0 or greater is required to use the spleeter package (for which only version 2.0 and up are available): https://pypi.org/project/spleeter/

**Comment by mhsmith** [comment]
For tensorflow-io-gcs-filesystem, see #776.

**Comment by asTravars33** [comment]
I need tensorflow 2.4.0 or higher I believe, as I am getting an error that "StringLookup" does not exist.

**Comment by Junaidnawab0835** [comment]
I need the following version to run YoloV5 Model:
tensorflow>=2.4.0
tensorflowjs>=3.9.0

On tensorflow 2.1.0 giving me this Error:
ValueError: Didn't find op for builtin opcode 'RESIZE_NEAREST_NEIGHBOR' version '3'
    Registration failed.

**Comment by mhsmith** [comment]
Not sure if this is useful for your application, but it should be possible to run YoloV5 with our current version of PyTorch (#477).

**Comment by JoseGeorges8** [comment]
I need TF 2.4 for Select-Ops https://www.tensorflow.org/lite/guide/ops_select#python

**Comment by basaris** [comment]
When I am trying to pip install tensorflow in my react-native app, it crashes and an error like this occurs:

Traceback (most recent call last):
  File "C:\Users\bill\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\bill\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\bill\Desktop\react-native\MapAdapt\android\app\build\generated\python/bp\chaquopy\pip_install.py", line 366, in <module>
    PipInstall().main()
  File "C:\Users\bill\Desktop\react-native\MapAdapt\android\app\build\generated\python/bp\chaquopy\pip_install.py", line 60, in main
    self.move_pure([ri.tree for ri in req_infos if ri.is_pure], abi, abi_trees[abi])
  File "C:\Users\bill\Desktop\react-native\MapAdapt\android\app\build\generated\python/bp\chaquopy\pip_install.py", line 179, in move_pure
    self.move_to_common(abi, path)
  File "C:\Users\bill\Desktop\react-native\MapAdapt\android\app\build\generated\python/bp\chaquopy\pip_install.py", line 206, in move_to_common
    renames(abi_filename, common_filename)
  File "C:\Users\bill\Desktop\react-native\MapAdapt\android\app\build\generated\python/bp\pip\_vendor\retrying.py", line 53, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\Users\bill\Desktop\react-native\MapAdapt\android\app\build\generated\python/bp\pip\_vendor\retrying.py", line 217, in call
    raise attempt.get()
  File "C:\Users\bill\Desktop\react-native\MapAdapt\android\app\build\generated\python/bp\pip\_vendor\retrying.py", line 252, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\Users\bill\Desktop\react-native\MapAdapt\android\app\build\generated\python/bp\pip\_vendor\six.py", line 703, in reraise
    raise value
  File "C:\Users\bill\Desktop\react-native\MapAdapt\android\app\build\generated\python/bp\pip\_vendor\retrying.py", line 204, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\Users\bill\Desktop\react-native\MapAdapt\android\app\build\generated\python/bp\chaquopy\pip_install.py", line 303, in renames
    os.renames(src, dst)
  File "C:\Users\bill\AppData\Local\Programs\Python\Python38\lib\os.py", line 270, in renames
    rename(old, new)
PermissionError: [WinError 5] ��� ����������� � ��������: 'C:\\Users\\bill\\Desktop\\react-native\\MapAdapt\\android\\app\\build\\pip\\debug\\arm64-v8a\\tensorboard' -> 'C:\\Users\\bill\\Desktop\\react-native\\MapAdapt\\android\\app\\build\\pip\\debug\\common\\tensorboard'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'C:/Users/bill/AppData/Local/Programs/Python/Python38/python.exe'' finished with non-zero exit value 1

Any idea why it crashes? Any help? When I pip install other libraries like numpy or scipy it loads fine. Please help.

**Comment by mhsmith** [comment]
I'm unlikely to make any more builds of the full TensorFlow package in the foreseeable future, because each upgrade is something like a full week's work, and the package is so big that it's barely even possible to include it in an app without going over Google Play's size limits.

If anyone wants to try and build it themselves, I will still accept a PR if you succeed. But I warn you that this will be extraordinarily difficult, far more so than any of our other recipes. So I won't be able to provide much support.

I'm sorry to anyone who's inconvenienced by this, but I only have so much time, and I have to prioritize things that will help the most people. 

Here are some alternatives:

* TensorFlow Lite (`tflite-runtime`) – See [the FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#faq-size) for migration instructions, and [#675](https://github.com/chaquo/chaquopy/issues/675) for updated versions.
* PyTorch (`torch`) – See [#606](https://github.com/chaquo/chaquopy/issues/606) for updated versions.
