### ISSUE TITLE
Restart python without restarting the app.

### ISSUE THREAD

**Issue by matsbohlinsson** [chaquo/chaquopy#382]
Is it possible to restart the interpretator from inside the app?
It would save some time when I change the python code, not to have to restart the app.
Thanks
Mats

I was thinking something like:

if (!Python.isStarted()) {
      Python.start(new AndroidPlatform(this));
 }
else
{
     **Python.stop();**
     Python.start(new AndroidPlatform(this));
}

Python python = Python.getInstance();
PyObject pythonFile = python.getModule(module_name);
PyObject rtt  = pythonFile.callAttr(...);

**Comment by mhsmith** [comment]
I don't think CPython reliably supports this, which is why Chaquopy doesn't support it either.

However, if you're loading Python code from a file at runtime, you could use [`importlib.reload`](https://docs.python.org/3/library/importlib.html#importlib.reload), or simply delete the module from `sys.modules` and then import it again.
