### ISSUE TITLE
Appending to file

### ISSUE THREAD

**Issue by mattw714** [chaquo/chaquopy#406]
I am trying to append items from a list to a file but after running the program the the values are never added to the file. I based my code off another thread on how to read files so I guess there would have to be a different way to tackle this. Here is what I have:

```
from os.path import dirname, join

mylist = ["test", "list", "XYZ"]
filename = join(dirname(__file__), "sample.txt")
with open(filename,"a") as filehandle:
      for listitem in mylist:
            filehandle.write('%s\n' % listitem)
```

**Comment by mhsmith** [comment]
You shouldn't write to `dirname(__file__)`, because that directory may be deleted next time you install the app. Instead, write your files under `os.environ["HOME"]`, which corresponds to your app's private files directory.

Aside from that, your code looks fine to me, but if you think it may be crashing then you should check whether there are any relevant errors in the [Logcat](https://developer.android.com/studio/debug/am-logcat.html).

**Comment by mattw714** [comment]
> You shouldn't write to `dirname(__file__)`, because that directory may be deleted next time you install the app. Instead, write your files under `os.environ["HOME"]`, which corresponds to your app's private files directory.
> 
> Aside from that, your code looks fine to me, but if you think it may be crashing then you should check whether there are any relevant errors in the [Logcat](https://developer.android.com/studio/debug/am-logcat.html).

Where can I find that directory on my computer ('/data/user/0/com.example.app/files/)?

**Comment by mhsmith** [comment]
You can see it in the [Device File Explorer](https://developer.android.com/studio/debug/device-file-explorer).
