### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by bibitte** [chaquo/chaquopy#421]
Hello,

I wrote an android port of a python application that analyse drone blackbox log.
I Just call the python code to do the analyse.

I have a problem of memory leak and that cause some crash on big blackbox log especially on a log with multiple record.
In my the code i I wrote and android service that split the blackbox log for each record that compose it, and i loop on each record to call python to analyse the record.
But Between each increment the native memory does not go down until crash.
You can see it on this profiling session : 
![profile4in1](https://user-images.githubusercontent.com/25138413/103467191-d2895180-4d4c-11eb-939d-d17d7b3d90c3.png)

But If I run separatly an analysis on each record I don't have the issue(I run 4 separate analysis on the 4 record on 4 blackbox file) (the memory go down after each call) : 
![profile4séparate](https://user-images.githubusercontent.com/25138413/103467387-dae28c00-4d4e-11eb-9e55-aa4f91cb33ee.png)
 
To reproduce this issue:
- Build my project (use **develop** branch and follow instructions on the readme to init submodule)
- use an **emulated nexus 4 on API 26**
- use black box log in attachement

usefull info :
- Link to my project : https://gitlab.com/bibitte/androidblackboxanalyser/-/tree/develop
- blockbox log to reproduce the issue (_btfl_001.bbl_ => 4 record in one log to reproduce the issue, / _btfl_00*.bbl_=> the splitted log to run setarate analysis without issue)
[blackbox.zip](https://github.com/chaquo/chaquopy/files/5760936/blackbox.zip)
- Code of the service : https://gitlab.com/bibitte/androidblackboxanalyser/-/blob/develop/app/src/main/java/com/androidblackboxanalyser/service/AnalysisService.java 
at line 250 that call  BlackBoxUtils.callPlasmatree(f, getApplicationContext(), cpt);
- see line 93 of : https://gitlab.com/bibitte/androidblackboxanalyser/-/blob/develop/app/src/main/java/com/androidblackboxanalyser/utils/BlackBoxUtils.java
 - python code that I Call : 
 https://gitlab.com/bibitte/androidblackboxanalyser/-/blob/develop/app/src/main/python/my_pid_analyser.py
(I tried to call directly the garbage collector without effect.)

If you have any questions please do not hesitate to contact me.

**Comment by mhsmith** [comment]
Thanks for the excellent report. 

Every figure created by `plt.figure` will be remembered by matplotlib until you until you call `plt.close`. The call to `plt.clf` in `_csv_iter` will clear the figure rather than closing it, which will free almost as much memory. But it only clears the most recent figure, and you're creating two.

When processing one record at a time, the temporary filename passed to `plt.figure` was the same every time, so it reused the previous figure objects instead of creating new ones. But when processing multiple records in a file, each record had a different suffix: 0, 1, 2, 3, so it created multiple figures.

The solution is to either:
* Call `plt.close` once you're finished with each figure, as described [here](https://stackoverflow.com/questions/2364945); or
* Use the figure API directly rather than going via `plt`, as described [here](https://stackoverflow.com/questions/16334588).

**Comment by bibitte** [comment]
I have just added plt.close('all') after each call and it works fine. 
I have searched with myself  few days without success (It's not my python code, and I'm not experimented in python and still less with mathplotLib).

Thank a lot!
