### ISSUE TITLE
How to handle infinite condition?

### ISSUE THREAD

**Issue by jay9440** [chaquo/chaquopy#456]
Greetings of the day, 

I am using chaquopy in production use and I am building an IDE for smartphone. I need to handle the situation, where student can write a code which runs into infinite loop, like following : 

```
while(True):
    print("Hello")
```

I tried using signal module and calling a method to terminate the code from python side after few seconds/minutes, but it didn't work 👎 . I have also tried to terminate the code from kotlin and dart side, but it terminated the dart/kotlin code, but not the python code. It still runs in the background and crashes the app.

**Comment by mhsmith** [comment]
If your app allows users to run arbitrary code, then there are two ways I'm aware of to interrupt it:

* Run the code in a separate thread, and use the internal function `PyThreadState_SetAsyncExc` to force that thread to throw a Python exception, as shown [here](https://github.com/tongjinlv/matatacode-android/blob/ad46b0ad0bbd10aac954364a66af931d8b982971/app/src/main/python/hello.py). However, the user code will still be able to catch the exception, and it won't be able to interrupt native code.
* Run the code in a separate process using the `androd:process` attribute in the AndroidManifest, and interrupt it by killing the process with a signal. This method may be slower because you'll be restarting Python each time, but it'll be more reliable.

**Comment by jay9440** [comment]
@mhsmith, is it possible to handle it from kotlin side? like using a timer I would run the code and throw exception from kotlin code only?

**Comment by jay9440** [comment]
@mhsmith for the first point, what do you mean by native code? is it kotlin or python code? also why terminating with signal won't work? can you also explain if and how can we do it from python side only? I have tried creating daemon thread, but that too didn't work.

**Comment by jay9440** [comment]
@mhsmith I am able to resolve the infinite loop issue using threading. here's the code. kindly give your feedback on this.

```
def closeProgram():
    exit()

def runNLTKConstraintCode(code):
    t = threading.Thread(target=mainNLTK,args=(code,),daemon=True)
    t.start()
    t.on_close = closeProgram # close the thread on complete, so you don't have to wait for all 30 seconds... 
    if(t.is_alive):
        sleep(30)        # waiting time of your choice 
        raise SystemExit
```

**Comment by mhsmith** [comment]
Raising `SystemExit` will only end the current thread. If you want to interrupt another thread running arbitrary code entered by a user, then the options in my previous comment are the only ones I know.

The [`threading`](https://docs.python.org/3/library/threading) documentation doesn't make this clear, but I think that when it says "The entire Python program exits when no alive non-daemon threads are left", that doesn't apply when Python is embedded in a non-Python program as Chaquopy does.

Terminating with a signal will always work if implemented correctly, but it will kill the entire app, which is why you'd need to use the `android:process` setting in your AndroidManifest to isolate the user code from the rest of the app. 

By "native code" I mean C or C++ code compiled by the Android NDK, which is included in high-performance libraries such as NumPy. But a well-written library will return control from native code to Python often enough that a Python exception will still be detected. So instead of using processes and signals, I suggest you try the `PyThreadState_SetAsyncExc` method first, since the two cases I mentioned where it won't work are relatively rare. The link in my previous comment provides a complete exampe.

**Comment by jay9440** [comment]
@mhsmith , can you provide an example or link for using process tag in android? I didn't a correct example of how to use process in android.

**Comment by mhsmith** [comment]
I don't have an example at hand, but here's a structure which worked for me in the past:

* Declare a service in AndroidManifest with a process tag, and an activity with no process tag.
* In the activity, call `startService` to start the service, and `stopService` to stop it. You can pass additional data in the intent extras.
* In the service, implement `onStartCommand` to receive the start request. It should run Python code on a background thread, otherwise the main thread will be blocked and it won't be able to receive the stop request.
* In the service, implement `onDestroy` to receive the stop request, and make it call `System.exit`. This will terminate the service process including the background thread, but will leave the main activity process alive.

These are all standard Android APIs, so please don't ask any more questions about them here: consult the Android documentation or StackOverflow instead.

Like I said, I suggest you try using `PyThreadState_SetAsyncExc` first, because it'll be much simpler than this.

**Comment by jay9440** [comment]
@mhsmith stopping thread using PyThreadState_SetAsyncExc worked like a charm. Thank you for the help.
