### ISSUE TITLE
How to use GPU with TensorFlow?

### ISSUE THREAD

**Issue by matsbohlinsson** [chaquo/chaquopy#458]
In chaquopy 9.0.0 **tensorflow-gpu** was added.

How to use it :-)

I only list  tensorflow-gpu:
            pip {
...
                install "tensorflow-gpu"
                install "numpy"
}

And when I run this code, no GPU's is available.
print("Num GPUs Available: " + str(len(tf.config.list_physical_devices('GPU'))))
>Num GPUs Available: 0

Thanks!

**Comment by mhsmith** [comment]
Since TensorFlow 2.0, the `tensorflow` and `tensorflow-gpu` packages are [actually the same](https://github.com/tensorflow/tensorflow/issues/39581). They only support GPU acceleration via CUDA, which won't work on Android.

We recently added TensorFlow Lite (package name `tflite-runtime`), which does have GPU support on Android, but last time I checked there's no way to access it through the Python API, only the Java and C++ ones.
