### ISSUE TITLE
Support for Pyserial or serial does not detect port 

### ISSUE THREAD

**Issue by Jaiv24** [chaquo/chaquopy#470]
When I press the button in the android application but somehow I am receiving could not open a port error like this.
`Process: com.example.firebaseheartratemonitor, PID: 16761
com.chaquo.python.PyException: SerialException: [Errno 2] could not open port COM4: [Errno 2] No such file or directory: 'COM4'
        at <python>.serial.serialposix.open(serialposix.py:325)
        at <python>.serial.serialutil.__init__(serialutil.py:244)`

Android Java code:
``` if (!Python.isStarted()){
            Python.start(new AndroidPlatform(this));
        }
        Python py = Python.getInstance();
        PyObject module = py.getModule("get");

        sendDataOverDisplay.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
              PyObject pyObject = module.callAttr("main", heartrate);

              sendData.setText(pyObject.toString());
            }
        });
```

Python Script:
```
import serial
import time
def main(data):
    with serial.Serial('COM4', 9600) as ser:
        ser.open()
        requiredData = data[0]
        ser.write((requiredData).encode())
        time.sleep(.01)
        ser.close()
        return requiredData
```

**Comment by mhsmith** [comment]
"COM4" looks like a Windows serial port name, so that won't work on Android. Try using something like [serial.tools.list_ports`](https://pyserial.readthedocs.io/en/latest/tools.html) to discover the correct name.

Also, even if you do use the correct name, your app probably still won't have permission to access the port directly. If you're running on a rooted device, you may be able to get pyserial to work by changing the permissions on the device file. On non-rooted devices, the only option I know of is to use the Java [`UsbManager`](https://developer.android.com/reference/android/hardware/usb/UsbManager) instead, perhaps with the help of a library like [UsbSerial](https://github.com/felHR85/UsbSerial). You can still call these APIs from Python with the help of the [Chaquopy Python API](https://chaquo.com/chaquopy/doc/current/python.html).
