### ISSUE TITLE
import PyObject from a class

### ISSUE THREAD

**Issue by Hilangli** [chaquo/chaquopy#478]
#### Chaquopy version
9.1.0

#### Relevant parts of your build.gradle file
ndkVersion '21.3.6528147'

#### Describe your issue
I am trying to add your SDK to an existing project. 
My problem is that I want to run the python script on demand, when the area of the code is a regular class, BUT I can't import PyObject from a regular class, I know that it can be import through an activity but the code flow doesn't allows it. There is a way to pass it? Or even to import it through Fragment?
Tnx :)

**Comment by mhsmith** [comment]
Do you mean you need a Context object in order to call `Python.start`? If you're writing a Fragment, you can always use the [`getContext`](https://developer.android.com/reference/androidx/fragment/app/Fragment#getContext()) method.

Or if you mean something else, please  be more specific about what you're tried and what the problem was.

**Comment by Hilangli** [comment]
WOW! Thanks for the quick answer!
I was trying to call it with context but it didn’t recognized Python object. I wrote it as follows:
if (! context.Python.isStarted()) {
    context.Python.start( context.AndroidPlatform(this))
}
The code is in a Fragment in function “OnViewCreated” and is written in Kotlin.
I get the error: “Unresolved reference: Python”

**Comment by mhsmith** [comment]
That's not the correct syntax at all. Please read [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#startup) more carefully.
