### ISSUE TITLE
"CCompiler.compile: Chaquopy cannot compile native code" When installing ChatterBot

### ISSUE THREAD

**Issue by itsybitsci** [chaquo/chaquopy#500]
![image](https://user-images.githubusercontent.com/61088479/118557986-96550b80-b798-11eb-8b80-775266f2593f.png)

I am getting this error when installing ChatterBot, I would really appreciate it if you can include this in the next update. Thanks!

**Comment by mhsmith** [comment]
The current version of Chatterbot requires Spacy version 2.1, but we currently provide version 2.2.3 (see #121).

You might be able to work around this by using a a slightly older version of ChatterBot. Try changing your install requirement from `"chatterbot"` to `"chatterbot==1.0.4"`.

**Comment by itsybitsci** [comment]
I have tried your suggestion and it worked. Thanks!

**Comment by mhsmith** [comment]
The Spacy requirement was removed in Chatterbot version 1.0.8, but that can't be installed either because it's been marked as requiring Python `'>=3.4, <=3.8'`, which, presumably by accident, excludes all 3.8.x versions. There are several complaints about this on the [Chatterbot issue tracker](https://github.com/gunthercox/ChatterBot/issues), but the project currently appears to be abandoned.

So the last version that works is still 1.0.4, as shown above.
