### ISSUE TITLE
cannot import name '_imaging' from 'PIL'

### ISSUE THREAD

**Issue by shojaeialireza** [chaquo/chaquopy#505]
Hello, I want use tesseract library in my android project. i copy PIL, pytesseract and pillow in python directory in my android project. but when import Image from PIL package this error is shown
cannot import name '_imaging' from 'PIL'

**Comment by mhsmith** [comment]
Instead of copying libraries into your source code directory, you should install them using the [`pip` block](https://chaquo.com/chaquopy/doc/current/android.html#requirements) in build.gradle. This will allow you to use PIL or Pillow.

However, pytesseract is not currently available for Chaquopy. Please see https://github.com/chaquo/chaquopy/issues/220#issuecomment-805972681 for a possible workaround.
