### ISSUE TITLE
Improve performance when casting python array to java

### ISSUE THREAD

**Issue by nhutthanh340** [chaquo/chaquopy#528]
I have array with shape [23, 14, 10, 9] returned from a function in java (input_shape=[1, 14, 10, 9], output_shape=[23, 14, 10, 9]) for python. It got a lot of time (about 6 seconds). I think the reason this array is so large when transferring data from python to java and back. I hope you suggest me to improve speed. Thanks

**Comment by nhutthanh340** [comment]
Can i pass data as reference parameter?

**Comment by mhsmith** [comment]
Can you post the relevant code?

**Comment by nhutthanh340** [comment]
Sorry, my out_shape = [[23, 2086], [23, 1]]
![image](https://user-images.githubusercontent.com/36669308/128270182-d005cc60-db56-40b7-8fba-992b15152464.png)
![image](https://user-images.githubusercontent.com/36669308/128270450-a8dff448-ae83-4386-bb94-0c5d6201deba.png)
![image](https://user-images.githubusercontent.com/36669308/128270797-173aeca7-0855-41b2-b5e3-4ace57779171.png)

**Comment by nhutthanh340** [comment]
with batch_size=1, it still long time

**Comment by nhutthanh340** [comment]
I have tested. Caused by PyObject's toJava() function when casting "data" parameter in python to "inputs" in java.

![image](https://user-images.githubusercontent.com/36669308/128298548-057dcf5f-30a7-46cc-bbe7-c4aa032bd3f8.png)

Can you get me the ideas to resolve it, please?

**Comment by mhsmith** [comment]
It looks like you've changed the code a lot, so I'll ignore all except your last comment.

Can you confirm the `PyObject data` is a Numpy array with shape [23, 14, 10, 9]?

What is the dtype of the array? You'll get better performance if the NumPy and Java data types are the same, i.e. `float` with `float32`, or `double` with `float64`.

How long does the `toJava` call take in the current version of the code?

> with batch_size=1, it still long time

How long exactly?

**Comment by nhutthanh340** [comment]
The shape [23, 14, 10, 9] is just an example. In fact, It has a shape that changes from [1, 14, 10, 9] to [512, 14, 10, 9].

I have tried 2 cases:
Case 1:
data = np.array(data, dtype=np.float32)
data = jarray(jarray(jarray(jarray(jfloat))))(data)

![image](https://user-images.githubusercontent.com/36669308/128437997-22acc4b8-47d3-4b25-b73b-bd6f2a7fd1c4.png)

and here are result:
![image](https://user-images.githubusercontent.com/36669308/128439086-177941ba-79a2-40a9-8176-be96db422964.png)

Case 2:
float[][][][] inputs = data.toJava(float[][][][].class);

![image](https://user-images.githubusercontent.com/36669308/128438226-a3fdc683-736e-4a50-bc19-b2b77a196243.png)

![image](https://user-images.githubusercontent.com/36669308/128438388-332195e4-8af4-4caf-95a6-a51d2bb4fe74.png)

and here is result:
![image](https://user-images.githubusercontent.com/36669308/128438913-263f5bcb-f78b-4fc3-b674-b8a42ef4b7d7.png)

Please point out my mistakes, thanks

**Comment by mhsmith** [comment]
I don't think you've made any mistakes, but unfortunately, converting large numbers of objects between Java and Python can be slow. And multi-dimensional arrays in Java do involve large numbers of objects, because an array of shape [batch_size, 14, 10, 9] is actually stored in `batch_size * 140` arrays of size 9.

However, I notice that in [your previous issue](https://github.com/chaquo/chaquopy/issues/526) you were using Chaquopy 6.3.0.  Please try upgrading to the current version 9.1.0, because there have been some major performance improvements in this area.

Upgrading to the current version will also give you access to the Python [`tflife_runtime`](https://www.tensorflow.org/lite/guide/python) package, which could allow you to avoid transferring this data between Python and Java at all.

**Comment by nhutthanh340** [comment]
Thank you for your help.
