### ISSUE TITLE
Crash: PyException raised with lambda functions as callback

### ISSUE THREAD

**Issue by StudentGGG** [chaquo/chaquopy#551]
Hi Chaquo team,

I get the following exception on 50% on the users with a public release on the Google play store. The crash happen on all sorts of devices with Android 9, 10 and 11. For instance the Mi 11 Lite 5G from Xiaomi or the Galaxy S9+ from Samsung.

Chaquopy version is 10.0.1.

```Fatal Exception: com.chaquo.python.PyException
NotImplementedError: kotlin.jvm.functions.Function1.invoke is abstract and cannot be called
<python>.java.chaquopy.JavaMethod.__call__ (JavaMethod.java:777)
<python>.java.chaquopy.JavaMethod.__get__.lambda2 (__get__.java:771)
```

In Kotlin, I call python with lambda function callbacks like this:
```
py.getModule("python_lib").callAttr("python_function",
                {if(!au.isCancelled()) successCallback()},
                {f : Float -> if(!au.isCancelled()) progressCallback(f)},
                {msg : String -> if(!au.isCancelled()) failureCallback(msg, null)})
```

And on the python side I do:
``successCallback.invoke()``
or
``progressCallback.invoke(float)``
or
``failureCallback.invoke(string)``

**Comment by mhsmith** [comment]
Yes, this may be related to minification. Do you have the [`minifyEnabled` or `isMinifyEnabled`](https://developer.android.com/studio/build/shrink-code) setting in your build.gradle file for the "release" build type? If so, are you able to reproduce the bug locally by setting the [build variant](https://developer.android.com/studio/run#changing-variant) to "release"?

Chaquopy automatically adds some Proguard settings to your app which should prevent anything within `kotlin.jvm.functions` from being minified. So I'm not sure why this is happening.

As it says in [the documentation](https://chaquo.com/chaquopy/doc/current/python.html#classes), if you pass an Java object to Python which implements a functional interface, then your Python code can call it like a function using `()` syntax. And that's exactly what the Electron Cash example from the FAQ does. For example, instead of `progressCallback.invoke(f)`, you should just be able to write `progressCallback(f)`. That may fix situations where the method name has been obfuscated, but the interface itself is still present at runtime.

It would still be helpful if you post the complete stack trace.
