### ISSUE TITLE
use chaquopy in Fragment cause license warning

### ISSUE THREAD

**Issue by showkeyjar** [chaquo/chaquopy#560]
#### Chaquopy version

com.chaquo.python:gradle:10.0.1

#### Devices or emulators where the issue happens

android 7.0

#### Relevant parts of your code

        if (! Python.isStarted()) {
            Python.start(AndroidPlatform(requireContext()))
            Log.i("Python","python start")
        }
        val py: Python = Python.getInstance()

then I transfer py into a CoroutineScope

#### Describe your issue

I use up codes for few weeks, and no problem.

but when I change my view into nav bar and move those codes into a Fragment,

then when I run app everytime I see license warnings: 

"Unlicensed copy, app will close at 10 seconds."

**Comment by mhsmith** [comment]
Chaquopy doesn't care whether you use a Fragment or not. However, if you've made some changes to the timing of when you start or use Python, then that could cause the license message to appear at a different time.

If you already have a Chaquopy license, please contact me by email and I'll try to help.

Otherwise, please follow the instructions on [our website](https://chaquo.com/chaquopy/license/) to get a license key.

**Comment by showkeyjar** [comment]
I find the problem:
when I move class to the package of license, it works, 
but when I move it to another, it toast warnings.

for example: 
license package is com.test.abc
and Fragment class com.text.abc.TestFragment is ok
but com.test.abc.ui.home.TestFragment is not ok

so, if I get a license, it can not change the package path, right?

but If my project is grow bigger, and I want to reconstruct class to sub packages, 

how can I do that?

**Comment by mhsmith** [comment]
Sorry, I don't understand. You refer to "package of license" as if you have a license, but then you say "if I get a license" as if you don't have one. 

Do you have a license key or not? If you do, please contact me by email and I'll try to help. 

Otherwise, please follow the instructions on [our website](https://chaquo.com/chaquopy/license/) to get a license key. I don't know enough about your app to explain why changing your package structure would change the license warning behaviour. But I can guarantee that if you get a license key, all the license warnings will disappear, and you can structure your app however you like.

**Comment by showkeyjar** [comment]
I have license

`
so, if I get a license, it can not change the package path, right?
`
this mean I can not move class to sub package

**Comment by mhsmith** [comment]
If you have a single-app license or open-source license, then the applicationId in your build.gradle file must be the one you chose when you got the license key. However, there's no need for this to be the same as the package name in your Java/Kotlin classes.

> I have license

I can't find your name in my license records. Please contact me [by email](https://chaquo.com/chaquopy/contact/) giving your license key, and I'll be able to help you there.

**Comment by showkeyjar** [comment]
whatever, I can run my app by moving python init code to parent package, my submit mail is zergskj@163.com

**Comment by mhsmith** [comment]
OK, so your app is this one? 

> https://gitee.com/knifecms/beauty/tree/master/App/tf-android

I see from our server logs that you had some license verification failures a few days before you opened this issue. As I said above, when you have a free open-source license, your key will only work with the application ID in your repository, `com.ml.projects.beautydetection`.

If you still need help on this issue, please push the working and the non-working versions of your app to separate branches in your repository, send me the links, and I'll look into it.
