### ISSUE TITLE
How do you os or subprocess ?

### ISSUE THREAD

**Issue by gorgeously-app** [chaquo/chaquopy#565]
Hello,
I have tried that:

def listdir():
	return os.popen('ls').read()

But nothing is return. So is this possible to print output of shell command?

Edit: 

I tried another one, which results in errors.

def listdir():
	return subprocess.check_output("ls", shell=True)

**Comment by mhsmith** [comment]
What errors did you get?

It works for me on the emulator, but hardware devices might not have `ls` on the path. I think its normal location is `/system/bin/ls`.

**Comment by gorgeously-app** [comment]
> What errors did you get?
> 
> It works for me on the emulator, but hardware devices might not have `ls` on the path. I think its normal location is `/system/bin/ls`.

I tried that but it gave me empty response. What is the default location ? Do I need to have storage permission ?

**Comment by mhsmith** [comment]
> I tried that but it gave me empty response. 

Then you're probably trying to list an empty or unreadable directory. The current directory on Android is not guaranteed to be anywhere in particular, so if you want to list a specific directory then you should put it on the command line. Or preferably, use standard Python APIs like `os.listdir` rather than running external commands.

> What is the default location ? 

The default location of what?

> Do I need to have storage permission ?

You'll need the storage permission in order to access the external storage directory. For other directories like your app's [internal storage directory](https://developer.android.com/training/data-storage/app-specific#internal), it doesn't make any difference.

However, if your app targets API level 29 or higher, direct access to the external storage directory is only possible for your app-specific subdirectory. See [the FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#faq-sdcard) for advice on reading files created by other apps.
