### ISSUE TITLE
 Connect to chaquo.com:443 [chaquo.com/138.68.74.36] failed: Read timed out

### ISSUE THREAD

**Issue by yangfeng1994** [chaquo/chaquopy#566]
#### Chaquopy version
com.chaquo.python:gradle:10.0.1

#### Relevant parts of your build.gradle file
![image](https://user-images.githubusercontent.com/23312254/142731438-3d4acccc-0a7b-4a72-b759-4e6ff68674d1.png)

![image](https://user-images.githubusercontent.com/23312254/142731461-a07feee8-d41b-4999-9e2f-27973992dac7.png)
![image](https://user-images.githubusercontent.com/23312254/142731470-e8061b94-f6ee-438c-b08e-19461b121f7e.png)
![Uploading image.png…]()

**Comment by yangfeng1994** [comment]
![image](https://user-images.githubusercontent.com/23312254/142731502-44b29f62-80cf-4d5f-87a9-d573c1ac58df.png)

**Comment by mhsmith** [comment]
I'm not aware of any problem with our server. There's probably something wrong with your internet connection, or if you're in China you may be affected by government censorship.

If the problem persists, use another connection or VPN which can access chaquo.com, and then follow the instructions [here](https://chaquo.com/chaquopy/doc/current/faq.html#faq-mirror) to make your own local mirror of our repositories.

**Comment by yangfeng1994** [comment]
OK, thanks. After reading the documentation, I still don’t understand how this is done. Can you give a demo for easy simulation and use?

**Comment by yangfeng1994** [comment]
I have turned on the proxy, and YouTube can be accessed normally

**Comment by mhsmith** [comment]
What part of the documentation don't you understand?

If you have a proxy which allows you to access chaquo.com, then you can just use that instead of making a local mirror. After you've completed the first build, Gradle and pip should cache their downloads so later builds will be faster.

You can configure pip to use a proxy server by using a [`pip { options }`](https://chaquo.com/chaquopy/doc/current/android.html#requirements) line to pass the [`--proxy`](https://pip.pypa.io/en/stable/user_guide/#using-a-proxy-server) option. 

The environment variables mentioned there will probably also work, as long as you make sure they take effect on the Gradle process, which may require logging out and in again on Windows. But the config file mentioned there won't work, because Chaquopy's version of pip ignores config files.
