### ISSUE TITLE
Loading a JSON model with XGBoost in chaquopy

### ISSUE THREAD

**Issue by angecas** [chaquo/chaquopy#571]
#### Describe your issue
 I am loading using this python script my json file

```
import xgboost as xgb
from os.path import dirname, join

from xgboost.sklearn import XGBClassifier
def main ():
	filename = join(dirname(__file__), "model.json")
	model = XGBClassifier()
	model.load_model(filename)
	imprimir=str(model.get_params())

	return str(imprimir)
```
How can i load my model?? the XGBClassifier() is working.

The load doenst work. this print was me doing tests

**Comment by mhsmith** [comment]
I assume it was you who posted [this StackOverflow comment](https://stackoverflow.com/questions/70187121/xgboost-json-model-in-android-studio-using-chaquopy/70193297#comment124090792_70193297), where you said the error was:

```
XGBoostError: [10:32:17] xgboost/include/xgboost/json.h:65: Invalid cast, from Null to Array
```

As mentioned in #518, this can probably be fixed by regenerating your model file with the same XGBoost version as Chaquopy uses (currently 1.1.1).
