### ISSUE TITLE
Issue when running from foreground service

### ISSUE THREAD

**Issue by devwithzachary** [chaquo/chaquopy#578]
#### Chaquopy version
10.0.1

#### Devices or emulators where the issue happens
Testing on Huawei P40

#### Relevant parts of your code
```

public int onStartCommand(Intent intent, int flags, int startId) {
        if (intent != null){
            if (intent.getAction() != null && intent.getAction().equals(ACTION_STOP_SERVICE)) {
                stopForegroundService();
            } else {
                new PythonTask(this).execute(intent);
            }
        }
        return super.onStartCommand(intent, flags, startId);
    }

public class PythonTask extends AsyncTask<Intent, Integer, Long> {
        Python py = Python.getInstance();

        private final Context context;

        public PythonTask (Context context){
            this.context = context;
        }

        @Override
        protected Long doInBackground(Intent... arg0) {

            PyObject module = py.getModule(pyClass);
            String result = "";
            int resultCode = 1100;
            if (method.equals("run_inference")) {
                resultCode = 1101;
                result = module.callAttr(method, userid, inference).toJava(String.class);
            } else if (method.equals("launch")) {
                result = module.callAttr(method, userid, serverAddress).toJava(String.class);
            } else {
                result = module.callAttr(method, userid).toJava(String.class);
            }
            module.close();

            Bundle bundle = new Bundle();
            bundle.putSerializable("result", result);
            bundle.putSerializable("file", fileToString(file));

            notificationManager.cancel(NOTIFCATION_ID);

            resultReceiver.send(resultCode, bundle);
            stopForegroundService();
            return null;
        }
    }
```

#### Describe your issue

When running a python method from a foreground service I'm finding that callAttr will only work the first time that service is called. 
On future runs of the service while the Service object is still instantiated the python code will execute however appears to hang after execution and never returns the result. 

Is there a correct way to close down a module after its been used? (other than .close() ) or a better way to reuse it?

Alternatively is it possible to just complete refresh the Python object instead so that its a fresh instance (And the old one is killed) every time the PythonTask is executed?

Thank you

**Comment by mhsmith** [comment]
In order to give a specific answer to this, I'd need to know what your Python code was actually doing. But here are some general suggestions.

First, Chaquopy doesn't interact with the Android component lifecycle, so the fact that you're running in a foreground service won't make any difference.

Where exactly is your app hanging? Try adding some `print` statements to your Python code, or some `Log` statements to your Java code, then check the [Logcat](https://developer.android.com/studio/command-line/logcat) to see which is the last line to be executed.

> Is there a correct way to close down a module after its been used? (other than .close() )

Calling `close` won't actually "close down the module", only remove the reference to it from Java. A reference to the module will continue to exist in  Python's `sys.modules`, and the next time you call `getModule` the existing module object will be returned without re-importing it. 

> or a better way to reuse it?

If your app depends upon repeatedly executing some top-level code in a Python module (i.e. outside of any function), then it would usually be better to move the code into a function so it can be called multiple times without re-importing the module.

However, if you absolutely do need to re-import a module from scratch, then you'll first have to remove it from `sys.modules`, like this:

In Python:
```
sys.modules.pop(yourModuleName, None)
```
Or in Java:
```
py.getModule("sys").get("modules").asMap().remove(yourModulename)
```

After that, the next call to `getModule` will execute the module's top-level code again, and return a fresh module object.

**Comment by devwithzachary** [comment]
Thank you for the advice! I will see if I can replicate with a simple python method to make it easier to highlight wheres it going wrong.

**Comment by devwithzachary** [comment]
But some extra info that i do have, with my python code I have:

```
def run_inference(user_id, item_list):
    ....
    scores = item_scores.detach().numpy().ravel()
    scores.sort()
    scores = scores[::-1]
    scores_string = ','.join([f'{x:.2f}' for x in scores[:10]])
    print("scores returned: {}".format(scores_string))
    return scores_string
```

This the method being run by `result = module.callAttr(method, userid, inference).toJava(String.class);`

The print statement within the python code is executed and I can see this in the logs, however with a break point on `module.close();` in my java code this line is never reached. Which is what has led me to the suggestion that for some reason the python code is hanging at the method return.

And as I mentioned it runs perfectly fine on the first time.

There is no code in the top level of the python module so I don't 'need' to re-import it just seems strange to me that on the first import it works fine.

**Comment by devwithzachary** [comment]
Going to close this issue after some more testing it seems to be more of lifecycle issues and not actually anything to do with this library. Thanks for your time!
