### ISSUE TITLE
Failed to install lib  in v12.0.0

### ISSUE THREAD

**Issue by Zaeem6100** [chaquo/chaquopy#630]
Failed to install opencv-python>=4.5.5.64 from https://files.pythonhosted.org/packages/3c/61/ee4496192ed27f657532fdf0d814b05b9787e7fc5122ed3ca57282bae69c/opencv-python-4.5.5.64.tar.gz (from deepface).

python interpreter 3.10.0
it was working perfect with  chaquopy11.0.0 but after update it leaves the error

**Comment by mhsmith** [comment]
This isn't caused by an update to Chaquopy, but by an update to deepface. If you look at the [deepface release history](https://pypi.org/project/deepface/#history), you'll see that when we last talked about this in #597, the current version was 0.0.74. So update your build.gradle or requirements.txt file to change `deepface` to `deepface==0.0.74`.

To be notified when we release a new version of opencv-python, please subscribe to #620.
