### ISSUE TITLE
Can Chaquopy support some packages？

### ISSUE THREAD

**Issue by xzq306** [chaquo/chaquopy#640]
The platform we are targeting is Android, using the Flutter framework, would like to ask the following questions:
1. Can Chaquopy run these libraries on an Android phone? Including Numpy, Scipy, Pandas, Obspy, PyWavelets for data processing such as wavelet decomposition.
2.At present，we're calling [Chaquopy](https://chaquo.com/chaquopy/doc/current/index.html) from Flutter. An error was reported after import numpy library and run the code. And there is no error message on Flutter. I would like to know if there is a way to display the error message.
3.Can Chaquopy run python files directly instead of text format.

**Comment by mhsmith** [comment]
> Can Chaquopy run these libraries on an Android phone? Including Numpy, Scipy, Pandas, Obspy, PyWavelets for data processing such as wavelet decomposition.

The current version of Chaquopy supports all of these libraries except Obspy, which we omitted when moving to Python 3.8 because of lack of demand. You can still use it by going back to Chaquopy 6.3.0 or earlier.

To add libraries to your app, edit its build.gradle file as shown [here](https://chaquo.com/chaquopy/doc/current/android.html#android-requirements).

> An error was reported after import numpy library and run the code. And there is no error message on Flutter. I would like to know if there is a way to display the error message.
> Can Chaquopy run python files directly instead of text format.

These are limitations of the [unofficial Chaquopy Flutter plugin](https://pub.dev/packages/chaquopy), not of Chaquopy itself. You might need to modify the plugin, or implement these features separately yourself. Unfortunately I'm not very familiar with Flutter, so I can't give any more details.
