### ISSUE TITLE
SSL certificate verify failed

### ISSUE THREAD

**Issue by UtsaChattopadhyay** [chaquo/chaquopy#674]
Chaquopy: Installing for armeabi-v7a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-7.0
Processing c:\users\u00646185\androidstudioprojects\chaquopy\app\numpy-1.17.4-3-cp38-cp38-android_16_armeabi_v7a.whl
Collecting chaquopy-openblas>=0.2.20 (from numpy==1.17.4)
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /pypi-7.0/chaquopy-openblas/
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)'))': /pypi-7.0/chaquopy-openblas/
This is the error message.
I have also attached a picture. Is this because of the proxy server in my workstation because I can download this in my local PC.
To try the easiest one, i downloaded the .whl file and kept it in the app folder, but getting the same error
Thanks.
![chaq2](https://user-images.githubusercontent.com/44424045/184848142-09c8a154-c22e-41e1-8848-606b29df9f47.PNG)

**Comment by mhsmith** [comment]
We don't have a self-signed certificate on our server, so it must be your proxy server. As it says [here](https://pip.pypa.io/en/stable/cli/pip_install/#ssl-certificate-verification), pip doesn't use your system certificate store by default, but you can point at it using the [`--cert`](https://pip.pypa.io/en/stable/cli/pip/#cmdoption-cert) option. Or you could disable certificate verification with the [`--trusted-host`](https://pip.pypa.io/en/stable/cli/pip/#cmdoption-trusted-host) option. Both of these can be passed to pip using an [`options`](https://chaquo.com/chaquopy/doc/current/android.html#android-requirements) line in your build.gradle file.

> To try the easiest one, i downloaded the .whl file and kept it in the app folder

If you want to install packages from a local folder instead of our server, make sure you lay the folder out the same way as [our repository](https://chaquo.com/pypi-7.0/) (one subdirectory per package), and then point at that folder with the [`-extra-index-url`](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-extra-index-url) option.

**Comment by UtsaChattopadhyay** [comment]
For installing it from local folder
python{
            pip{
                options "--index-url", "https://pypi.org/simple/"
                options "--extra-index-url", "numpy"          

            }
}
SHould the pip block look like this?

**Comment by UtsaChattopadhyay** [comment]
Thanks. I have followed the same configuration and kept the numpy and chaquopy_openblas files there. But when i do import numpy as np, the app doesnt load. Should there be any install? thanks
python{
            pip{
                options "--index-url", "https://pypi.org/simple/"
                options "--extra-index-url", "packages"
            }
        }

**Comment by UtsaChattopadhyay** [comment]
I have deleted the numpy and openblas packages from the folders to keep it under 25mb
[Chaquopy_del.zip](https://github.com/chaquo/chaquopy/files/9368241/Chaquopy_del.zip)

**Comment by mhsmith** [comment]
> when i do import numpy as np, the app doesnt load. Should there be any install?

Yes, you should add this line to the `pip` block:

```
install "numpy"
```

If your app crashes again, you can find the error message in the [Logcat](https://stackoverflow.com/a/23353174).

**Comment by UtsaChattopadhyay** [comment]
yeah. After that I get 
 ERROR: Could not find a version that satisfies the requirement chaquopy-libgfortran>=4.9 (from numpy) (from versions: none)

**Comment by mhsmith** [comment]
Then you'll have to download that package to your local mirror as well.

**Comment by UtsaChattopadhyay** [comment]
This is how the build.gradle looks like
python{
            pip{
                options "--index-url", "https://pypi.org/simple/"
                options "--extra-index-url", "packages"
                install "numpy"
            }
        }
app
    build.gradle
    packages
        numpy
            numpy-XXX.whl
        chaquopy-openblas
            chaquopy_openblas-XXX.whl
        chaquopy-libgfortran
            chaquopy-libgfortran-XXX.whl
![ch1](https://user-images.githubusercontent.com/44424045/185531583-e3267aa3-092a-4188-838d-00cd8f8c1f53.PNG)
Downloaded from this link... I am still getting this error. Is this something related to my computer?
Thanks
https://chaquo.com/pypi-2.1/

**Comment by UtsaChattopadhyay** [comment]
If i want to disable certificate verification,
 python{
            pip{                
                options "--trusted-host","https://pypi.org/simple/"
                options "--trusted-host","https://chaquo.com/pypi-7.0"
                install "numpy"
            }
        }
SHould this be the appropriate command?

**Comment by mhsmith** [comment]
Please post code and logs using [code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks), otherwise GitHub will mess up the formatting.

> Downloaded from this link... I am still getting this error. 
> https://chaquo.com/pypi-2.1/

The correct link is https://chaquo.com/pypi-7.0. Why did you use pypi-2.1? Is it still mentioned in the documentation somewhere?

> If i want to disable certificate verification,
> SHould this be the appropriate command?

No, just the pass the domain name, not the entire URL. Please look for examples of this option on StackOverflow or elsewhere.

**Comment by UtsaChattopadhyay** [comment]
Why did you use pypi-2.1? Is it still mentioned in the documentation somewhere?

I think I searched for a package but this link came up. But thanks, I could use the packages I downloaded from my local folder. SSL one I couldnt solve, but okay.

**Comment by mhsmith** [comment]
>I think I searched for a package but this link came up. 

Just follow the instructions in [the FAQ](https://chaquo.com/chaquopy/doc/current/faq.html#faq-mirror) and you should be fine.
