### ISSUE TITLE
How to support ABI 'x86_64' and 'armeabi'?

### ISSUE THREAD

**Issue by ZhangKuixun** [chaquo/chaquopy#69]
I want support ABI 'x86_64' and 'armeabi' in my project. Are there better ways to solve problems?

**Comment by ZhangKuixun** [comment]
I used "com.chaquo.python:gradle:5.0.0"

**Comment by mhsmith** [comment]
x86_64 is not yet available, but we're likely to add it in the next few months. Please subscribe to #61 for updates. Meanwhile, you can build your app with the x86 ABI and it will still work on an x86_64 emulator.

"armeabi" (ARMv5) is obsolete. Chaquopy provides the newer ABI armeabi-v7a, which is supported by virtually all devices made since 2012.

**Comment by mhsmith** [comment]
x86_64 is now supported in Chaquopy 6.0.0.
