### ISSUE TITLE
Reading two files in the python script leads to "file not found" for the second file

### ISSUE THREAD

**Issue by drishtadyumna** [chaquo/chaquopy#690]
I am trying to implement my own example, by extending this matplotlib example. I am reading two files in the python script. Both are in the same folder called "resources" that I have created in the same directory as this python script. 

```
    sample_path = os.path.join(os.path.dirname(__file__), "resources", "sample.npy")
    with open(sample_path, 'rb') as f:
        sample = np.load(f)

    model_path = os.path.join(os.path.dirname(__file__), "resources", "model.pickle")
    with open(model_path, 'rb') as handle:
        model = pickle.load(handle)
```
The first file "sample.npy" is read, but the second file "model.pickle" gives the error that there is no such file in the provided path. When I switch the two such that the "model.pickle" file is read first, that is executed successfully, but the second one "sample.npy" then gives the no such file error.

So, file reading only works once for some reason.

**Comment by drishtadyumna** [comment]
1) Chaquopy version 12.0.1

2) Yes, that folder has 3 files in total. Apart from these two, there is a "requirements.txt" file that I use with pip in the gradle file, which works as expected. This "resources" folder is in the same directory as the python script i.e "src\main\python"

3) Where should I look in the Device File ?

This is what I see in Logcat when I read the sample file first - [https://i.imgur.com/YVBdrbH.png](https://i.imgur.com/YVBdrbH.png)

This when I read the model file first [https://i.imgur.com/okPBFft.png](https://i.imgur.com/okPBFft.png)

**Comment by mhsmith** [comment]
I think you've posted the wrong images: neither of them show a file not found error message, or any of the relevant filenames. In any case, please post logs as text, not images. That makes it easier for me to search, and for other people to find the issue if they're receiving the same messages.

If you are getting a file not found error, it should give the full path which you can then check in the Device File Explorer.

**Comment by drishtadyumna** [comment]
That file not found error shows up on the emulator (Nexus_5_API_31 in my case). I cannot find it on the Logcat anywhere. I am passing the file names to the python script exactly like the matplotlib example, and determining the full path of them as I have shown in the code. The file not found error is happening inside the python code, but I don't know where they are logged. I am seeing that error on the emulator -  [https://i.imgur.com/5pL3PI4.png](https://i.imgur.com/5pL3PI4.png)

I found the resources folder on the Device File Explorer. It's at 'data/user/0/com.chaquo.myapplication/files/chaquopy/app/resources' - [https://i.imgur.com/RqKv8Fn.png](https://i.imgur.com/RqKv8Fn.png)

I know if I could see that error I see on the emulator written in full on a log somewhere, that would be helpful. But I don't know where to look for that.

**Comment by mhsmith** [comment]
Since the full filename isn't visible in the toast, why do you think that the first file is being read successfully and the second one is failing?

You can log the filename from your Python code by simply [`print`ing it to stdout](https://chaquo.com/chaquopy/doc/current/android.html#sys). Examine it carefully and see if it corresponds to the path in the Device File Explorer. 

Most likely, you've made a mistake with the relative path. Your current code assumes that the Python file is at the root of the source code, directory, alongside the `resources` directory. If this isn't the case, then you'll have to add some `..` elements, as shown in [the documentation](https://chaquo.com/chaquopy/doc/current/android.html#android-data).

In future, please upload images to GitHub by dragging them into the issue. Not only does this make it easier to browse the issue, it also removes any risk of the link going dead in the future. But like I said, if the link *only* contains text, then just copy and paste the text.

**Comment by drishtadyumna** [comment]
```
I/python.stdout: sample path - /data/data/com.chaquo.myapplication/files/chaquopy/AssetFinder/app/resources/sample.npy
I/python.stdout: model path - /data/data/com.chaquo.myapplication/files/chaquopy/AssetFinder/app/resources/model.pickle
```

And from the device explorer I can see that the paths are correct. These are paths I copied from there

```
/data/data/com.chaquo.myapplication/files/chaquopy/AssetFinder/app/resources/sample.npy
/data/data/com.chaquo.myapplication/files/chaquopy/AssetFinder/app/resources/model.pickle
```

**Comment by drishtadyumna** [comment]
While adding the stdout lines, somehow I must have changed something. Now I can read both files. You are probably right -  I must have made a mistake somewhere in determining the paths. Thanks for your help.
