### ISSUE TITLE
Eliminate Chaquopy notification category

### ISSUE THREAD

**Issue by pcanas** [chaquo/chaquopy#703]
If I go to the notification settings of my app, there is a category for Chaquopy.
I would want to avoid showing this category to my end user. Is there any way I could do so?

**Comment by mhsmith** [comment]
This category was used only for the license notification. Since Chaquopy is now open-source, apps built with versions 12.0.1 and later will no longer create the category. However, the category will continue to show on any devices which used to have an older version of the app. The number of such devices will naturally go down over time.
