### ISSUE TITLE
Unable to use newer version of pycryptodomex / pycryptodome

### ISSUE THREAD

**Issue by Ansh1248163264** [chaquo/chaquopy#807]
> Task :app:generateDebugPythonRequirements
Chaquopy: Installing for arm64-v8a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-7.0, https://chaquo.com/pypi-13.1
Collecting pycryptodomex==3.15.0
  Using cached pycryptodomex-3.15.0.tar.gz (4.5 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\anshu\AppData\Local\Programs\Python\Python311\python.exe' -S -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\anshu\\AppData\\Local\\Temp\\pip-install-c0ab3b5i\\pycryptodomex\\setup.py'"'"'; __file__='"'"'C:\\Users\\anshu\\AppData\\Local\\Temp\\pip-install-c0ab3b5i\\pycryptodomex\\setup.py'"'"';import chaquopy_monkey; chaquopy_monkey.disable_native();f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base 'C:\Users\anshu\AppData\Local\Temp\pip-pip-egg-info-sixnk9vl'
    ERROR: Command errored out with exit status 1:

         cwd: C:\Users\anshu\AppData\Local\Temp\pip-install-c0ab3b5i\pycryptodomex\
    Complete output (19 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\anshu\AppData\Local\Temp\pip-install-c0ab3b5i\pycryptodomex\setup.py", line 488, in <module>
        set_compiler_options(package_root, ext_modules)
      File "C:\Users\anshu\AppData\Local\Temp\pip-install-c0ab3b5i\pycryptodomex\compiler_opt.py", line 341, in set_compiler_options
        clang = compiler_is_clang()
                ^^^^^^^^^^^^^^^^^^^
      File "C:\Users\anshu\AppData\Local\Temp\pip-install-c0ab3b5i\pycryptodomex\compiler_opt.py", line 251, in compiler_is_clang
        return test_compilation(source, msg="clang")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\anshu\AppData\Local\Temp\pip-install-c0ab3b5i\pycryptodomex\compiler_opt.py", line 82, in test_compilation
        objects = compiler.compile([fname], extra_postargs=extra_cc_options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\android\DRIVE C PROJECTS\Compressed\ANdroid_STUDIO\AndroidStudioProjects\demo\app\build\generated\python\bp\chaquopy_monkey.py", line 56, in compile
        chaquopy_block_native("CCompiler.compile")
      File "D:\android\DRIVE C PROJECTS\Compressed\ANdroid_STUDIO\AndroidStudioProjects\demo\app\build\generated\python\bp\chaquopy_monkey.py", line 87, in chaquopy_block_native
        raise DistutilsPlatformError("{}: {}".format(prefix, CHAQUOPY_NATIVE_ERROR))
    distutils.errors.DistutilsPlatformError: CCompiler.compile: Chaquopy cannot compile native code
    Testing support for clang
    ----------------------------------------
ERROR: Failed to install pycryptodomex==3.15.0 from https://files.pythonhosted.org/packages/52/0d/6cc95a83f6961a1ca041798d222240890af79b381e97eda3b9b538dba16f/pycryptodomex-3.15.0.tar.gz#sha256=7341f1bb2dadb0d1a0047f34c3a58208a92423cdbd3244d998e4b28df5eac0ed.
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Failed to install pycryptodomex==3.15.0 from https://files.pythonhosted.org/packages/52/0d/6cc95a83f6961a1ca041798d222240890af79b381e97eda3b9b538dba16f/pycryptodomex-3.15.0.tar.gz#sha256=7341f1bb2dadb0d1a0047f34c3a58208a92423cdbd3244d998e4b28df5eac0ed.

Chaquopy: Exit status 1

> Task :app:generateDebugPythonRequirements FAILED
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command 'C:/Users/anshu/AppData/Local/Programs/Python/Python311/python.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by Ansh24816** [comment]
I need this package as a requirement for installing other package 
Even it will be very helpfull if someone can help me to explain how can i build a custom package , like one we install with pip in #chaquopy , #AndroidStudio

**Comment by Ansh24816** [comment]
"pycryptodomex==3.9.4" is only compatible in android studio , but it's really depriacted and of no use, need help in newer version of this package for chaquopy

**Comment by mhsmith** [comment]
As you can see from [the repository](https://chaquo.com/pypi-7.0/pycryptodomex/), we don't have this version of pycryptodomex, but we do have version 3.9.4.

**Comment by mhsmith** [comment]
I see from my emails that you posted some other comments saying version 3.9.4 is "of no use". If you've deleted those comments, then maybe you changed your mind about that. Otherwise, please explain why you need the new version.

**Comment by mhsmith** [comment]
We're not planning to update this package in the near future, but if you'd like to try building the new version yourself, follow the instructions [here](https://github.com/chaquo/chaquopy/tree/master/server/pypi). And if you're successful, please make a pull request so we can add the new version to the public repository.

If anyone else needs a newer version of this package, please click the thumbs up button above, and post a comment explaining why you need it.

**Comment by Ansh24816** [comment]
Hello , Thankyou so much for your attention on this issue , I was just adding a python pip package , and on it's requirements there was issue with this "pycryptodomex" .
 { I was wondering if there was a option to remove this requirement ( like in gradle we have option to 'exclude' on adding any third party package ,  So , i want to ask is there any way in #chaquopy to exclude requirements , while adding any package through pip. }

Thanks Again for dropping the link for "building of new version" , sure i would give it a try ...  ( currently ,I am successfully using "pycryptodomex 3.9.4" ,  {Thanks For Making It Available}, I solved my problem by using lower version of that python package , because it was asking for latest version of "pycryptodomex" , and currently by god grace things are working fine in my android project.

**Comment by Ansh24816** [comment]
Hello , Thank you so much for your concern on my issue , i was trying to
add package of 'instagrapi' latest version  , and there i was seeing this
error of pycryptodomex , [pycrptodome was getting installed without any
burden]

I just removed my comment because i just got nervous   it's first time i
used github to raise issue .lol sorry ...


And thankyouu so much and claps for your hard work in making this amazing
#Chaquopy

Loved it , seriously.


A small request[ if ever i got issues related to chaquopy , can you please
help me, sometimes someone presence is enough 😊 i was having dream  to
combine completely java with python , #PJava , ( liveliness of java and
smartness of python ) , hence perfect mobile apps ..




I was having one more minor issue bro, as you mentioned in your docs ,
about the ndk , and the size they gain on including them , hence , google
play_console can't help much with reducing the size,  So , you explained
about making different flavours,

I just did the same , but making the flavours were like cross product of
flavours and builds , and for me i didn't saw no reduced size of apks

😅😅 Just telling that i saw that 😅😅


😂and i loved it ,  like my english techer you cut my bad english and make
the perfect grammar there😂

**Comment by mhsmith** [comment]
>  I was wondering if there was a option to remove this requirement ( like in gradle we have option to 'exclude' on adding any third party package , So , i want to ask is there any way in #chaquopy to exclude requirements , while adding any package through pip.

As far as I know, pip doesn't have any way to do that.

**Comment by mhsmith** [comment]
The best option I can think of is:
* Make a complete list of all your packages along with their indirect requirements. You can extract this list from the pip output shown while building your app, then convert it to the correct format with some simple find-and-replace operations.
* Remove the requirement you don't want.
* Install the list with the `--no-deps` option.

**Comment by Ansh24816** [comment]
> > I was wondering if there was a option to remove this requirement ( like in gradle we have option to 'exclude' on adding any third party package , So , i want to ask is there any way in #chaquopy to exclude requirements , while adding any package through pip.
> 
> As far as I know, pip doesn't have any direct way to do that. The best option I can think of is:
> 
> * Make a complete list of all your packages along with their requirements. You can extract this list from the pip output shown while building your app, then convert it to the correct format with some simple find-and-replace operations.
> * Remove the requirement you don't want.
> * Install the list with the `--no-deps` option.


Yes 
https://stackoverflow.com/questions/33441033/pip-install-to-custom-target-directory-and-exclude-specific-dependencies
(Some Alien Language)

**Comment by mhsmith** [comment]
I had a quick look at this when doing #1049, but the patch doesn't apply on any newer pycryptodome version. However, it's a fairly simple patch, so updating it should not be too hard.

**Comment by mhsmith** [comment]
pycryptodome and pycryptodomex version 3.21.0 is now available for Python 3.13.
