### ISSUE TITLE
Failed to install vispy

### ISSUE THREAD

**Issue by MarwanAdel1** [chaquo/chaquopy#833]
Failed to install vispy==0.12.2 from https://files.pythonhosted.org/packages/f7/20/c9b3080dcdcb11b78085f9dc4bf4ce9a7bae02ce18a923d235779ef8a6bb/vispy-0.12.2.tar.gz#sha256=141c2ddccc1158555bc89f09010c4b1d754487e816357333f31e795a7146a024.

**Comment by mhsmith** [comment]
This package contains native components, so it would have to be built into a wheel file. If you'd like to try doing this yourself, follow the instructions [here](https://github.com/chaquo/chaquopy/tree/master/server/pypi). And if you're successful, please make a pull request so we can add the package to the public repository.

Although Android does support OpenGL, I expect there will be some differences from the other platforms vispy supports, so that may require some extra work beyond just compiling the package.

If anyone else wants this package too, let us know by clicking the thumbs-up button above.

**Comment by mhsmith** [comment]
It's been over a year, and only one person has requested this package, so we won't be building it in the foreseeable future.

If anyone else wants this package, please post a comment, and I'll reopen the issue.
