### ISSUE TITLE
Running a python application which itself calls underlying python code.

### ISSUE THREAD

**Issue by bill-varney** [chaquo/chaquopy#847]
We are building a python application 'calling' many underlying python modules.
We want to know if this is possible with Chaquopy.
For instance, we will be utilizing from our application processes and/or threads
JSON
MsgPack
Cryptography services (AES/SHA1024/RSA, etc)
Sqlite3

and others.

Can we build a complete and layered python application and 'call' it
from Chaquopy and just let it do everything in python.
We may be using multiple-threads or even multiple processes.

**Comment by mhsmith** [comment]
Chaquopy supports all the packages you listed:
* JSON and Sqlite3 are in the Python standard library.
* MsgPack has a pure-Python implementation.
* Cryptography and pycryptodome are both in our [binary package repository](https://chaquo.com/pypi-7.0/).

To check whether a package is supported, just try adding it to your build.gradle file, as shown [here](https://chaquo.com/chaquopy/doc/current/android.html#android-requirements).

Chaquopy also supports multiple threads. However, support for multiple processes is limited, as there is no `python` executable to call, and `multiprocessing` doesn't work either because Android doesn't support System V IPC. For some cases, you might be able to call `os.fork` directly. Or you could create multiple independent process by using the `process` attribute of the AndroidManifest.xml file,
