### ISSUE TITLE
Using the pip yolov5 package: "Failed to install shapely>=1.8.0"

### ISSUE THREAD

**Issue by jonasMayr314** [chaquo/chaquopy#877]
Hey,

I want to include the yolov5 package from ultralitycs. (see. https://pypi.org/project/yolov5/)
During building the Gradle Build I get the following stack trace:

`Failed to install shapely>=1.8.0 from https://files.pythonhosted.org/packages/10/a7/de139da3ce303101c357a9ba801328cba85cf6ace157da31a4007bca85e4/shapely-2.0.1.tar.gz#sha256=66a6b1a3e72ece97fc85536a281476f9b7794de2e646ca8a4517e2e3c1446893 (from sahi>=0.11.10->yolov5).`

For me it look like some sub packages yolov5 uses are not installed correctly / are not supported in 
chaquopy. Did someone already solve this issue? Any tipps? 
Is there a way to install all submodules / packages yolov5 requires? 

Thanks in advance!

**Comment by mhsmith** [comment]
It looks like your app is using Python 3.8, which is correct, because yolov5 depends on `torch` and probably some other packages which we've only built for Python 3.8 so far.

However, some of our Python 3.8 packages are at older versions, including shapely, which is currently at [version 1.7.0](https://chaquo.com/pypi-7.0/shapely/). Fortunately, we already have a [recipe for shapely 1.8.5](https://github.com/chaquo/chaquopy/tree/master/server/pypi/packages/shapely), so all you should need to do is build this recipe for Python 3.8 by following the instructions [here](https://github.com/chaquo/chaquopy/blob/master/server/pypi/README.md).

When I tried to install yolov5, I actually got a different error:

`Failed to install grpcio>=1.48.2 from https://files.pythonhosted.org/packages/cb/82/f4a1535e6ae5360abd59ab4e8d90a884c680a3997a44c7418364030874dd/grpcio-1.54.2.tar.gz#sha256=50a9f075eeda5097aa9a182bb3877fe1272875e45370368ac0ee16ab9e22d019 (from tensorboard>=2.4.1->yolov5)`

This could be fixed by using an older version of `tensorboard` (https://github.com/chaquo/chaquopy/issues/843#issuecomment-1497120161), or building a newer version of `grpcio` (#873).

**Comment by mhsmith** [comment]
If you've built the chaquopy-geos wheel yourself, then it should be in `server/pypi/dist/chaquopy-geos`. However, it's much easier for you to download it to that location from one of our repositories:
* https://chaquo.com/pypi-7.0/
* https://chaquo.com/pypi-13.1/

The same is true of any other package listed in the `host` section of a meta.yaml file.

**Comment by mhsmith** [comment]
Shapely 1.8.5 for Python 3.8 has now been added to [the repository](https://chaquo.com/pypi-13.1/).
