### ISSUE TITLE
android studio giraffe can't add python to defaultConfig

### ISSUE THREAD

**Issue by AsitDixit** [chaquo/chaquopy#934]
Everything is working but when I add python to defaultConfig I get error.
![Screenshot (57)](https://github.com/chaquo/chaquopy/assets/93305670/7a0e191b-96e7-478f-806a-1a839b064e89)

**Comment by mhsmith** [comment]
This is because the current stable version of Chaquopy doesn't support KTS files (#231). However, we've already fixed this in the development version, so I'll give you a link to a pre-release build tomorrow.

**Comment by AsitDixit** [comment]
> This is because the current stable version of Chaquopy doesn't support KTS files (#231). However, we've already fixed this in the development version, so I'll give you a link to a pre-release build tomorrow.

@mhsmith Sir any update?

**Comment by Gelassen** [comment]
The same issue. Do you have any news on this?

**Comment by Gelassen** [comment]
@AsitDixit , by link above a promising workaround has been offered:
```
[albaspazio](https://github.com/albaspazio) commented [Apr 15, 2023](https://github.com/chaquo/chaquopy/issues/231#issuecomment-1509633451) •

in the meanwhile.....I wrote a simple tutorial with a suggestion to deal with this issue.
https://medium.com/p/d9739e95a05a
simply put all python code in a same library module with groovy build language and consume it from other app/lib modules built in kts.
```

**Comment by mhsmith** [comment]
Here's how to use the pre-release build with KTS support:

* At the top level of your project, edit the settings.gradle or build.gradle file to add this line to the `repositories` block within `pluginManagement` or `buildscript` (NOT within `allprojects` or `dependencyResolutionManagement`):
  ```
          maven { url = uri("https://chaquo.com/maven-test") }
  ```

* Edit the build.gradle file to change the Chaquopy version to `15.0.0`.

* In KTS files, you'll need to configure Chaquopy using a top-level `chaquopy` block, rather than the `python` block within `android`. For details, see the [Chaquopy 15 documentation](https://chaquo.com/chaquopy/doc/15.0/android.html).

**Comment by Gelassen** [comment]
@mhsmith , thank you for work on this! Please update [doc](https://chaquo.com/chaquopy/doc/15.0/android.html#project-setup) with reference on this ```maven { url = uri("https://chaquo.com/maven-test") }```

**Comment by mhsmith** [comment]
There's no point in doing that, because the only place that version of the documentation is currently linked is from the comment above.

**Comment by jercylew** [comment]
I convert the build.gradle of kotlin to groovy, and it works

**Comment by mhsmith** [comment]
If you're using the pre-release version 15.0.0 above, please now switch to the stable version 15.0.1, which was released today.
