### ISSUE TITLE
Build missing packages for Python 3.9 - 3.12

### ISSUE THREAD

**Issue by IsakTheHacker** [chaquo/chaquopy#972]
Python 3.11 has been supported for about a year now but no packages are built targeting this Python version. WHY!?

**Comment by IsakTheHacker** [comment]
Better support for Python 3.11 would probably also make apps faster on average and improve the startup time according to this: https://docs.python.org/3/whatsnew/3.11.html#optimizations

**Comment by mhsmith** [comment]
Yes, we should look into this. I'll add it to the milestone for the next version, when we'll be adding Python 3.12 as well.

**Comment by mhsmith** [comment]
The following packages are now available for Python 3.11: 
* `murmurhash cffi pillow regex pynacl zstandard aiohttp bcrypt brotli cymem cytoolz frozenlist greenlet multidict ruamel-yaml-clib srsly yarl numpy pandas pywavelets kiwisolver contourpy matplotlib argon2-cffi bitarray editdistance ephem lru-dict pyzbar typed-ast netifaces wordcloud pycurl preshed`

This is the same list as we released last year for Python 3.9 and 3.10, minus:
* `twisted` – is now a pure-Python package.
* `pycrypto pysha3 backports-zoneinfo` – have all been declared obsolete.
* `cryptography` – we're currently stuck on version 3.4.8 until we have Rust support ([#657](https://github.com/chaquo/chaquopy/issues/657)), and that version isn't compatible with OpenSSL 3. I came up with an awkward workaround to build it for Python 3.9 and 3.10, but rather than do that again, my time would be better spent dealing with the Rust issue.

I'll add more Python 3.9 - 3.11 packages later, but first I'll look at 3.12.

**Comment by mhsmith** [comment]
The same packages are now available for Python 3.12, minus:
* `wordcloud` – doesn't support Python 3.12 yet.

**Comment by mhsmith** [comment]
I've also added the following combinations which didn't previously exist:
* `grpcio` for Python 3.9 - 3.12
* `scikit-image` for Python 3.9 - 3.10
* `scikit-learn` for Python 3.10

**Comment by arijit4** [comment]
Can `pycryptodome` be added?

**Comment by mhsmith** [comment]
OK, `pycryptodome` and `pycryptodomex` version 3.9.4 have now been added for Python 3.9 - 3.12. This was the newest version that built with the current patch. If anyone needs a newer version, see #807.

**Comment by IsakTheHacker** [comment]
@mhsmith Could you build Python 3.11 and 3.12 wheels for miniaudio?

**Comment by mhsmith** [comment]
OK, I'll give it a try. And for future reference, here's a list of all the packages which were added since the initial 3.9 and 3.10 build: `jpegio tgcrypto lameenc pyproj astropy pyerfa qutip photutils miniaudio lz4 soxr aubio pycocotools zope.interface`

**Comment by mhsmith** [comment]
The packages in the previous comment have now been added for Python 3.11 and 3.12, except `qutip` and `photutils`, which depend on SciPy and therefore have only been added for Python 3.9 and 3.10.

**Comment by mhsmith** [comment]
I don't have time to add any more packages at the moment, but lxml shouldn't be too difficult to build yourself – see https://github.com/chaquo/chaquopy/issues/816#issuecomment-1450283229.

**Comment by mhsmith** [comment]
If anyone has more package requests for Python 3.9 or later, please search to see if there's an existing issue you can vote for, and create a new issue if you can't find one.
